### ISSUE TITLE
Access Control for the IP Reservation Mamangement

### ISSUE THREAD

**Issue by jeevanions** [Azure/ipam#106]
Use Case: 

We would like to restrict the IP Reservations management only to the users/groups who created them. At the same time, the admins have access to all of the reservations. 

At the moment, I guess the GET API call would return all the IP reservations on the system.

Is there any off-the-shelf option for this requirement? Can we use Azure RBAC somehow?

Another option is the create a custom resource in Azure using "Azure Custom Resource Providers" so we can have the IP Reservations stored in respective subscriptions, and at the same time, we have this like a state that we can use.

**Comment by jeevanions** [comment]
Hi @DCMattyG, I just tested this, and it looks like it already covers this use case.

I created different IP reservations from different SPs and used the access token for these SPs to query for the reservations. It only returned the ones created by the SP. That is really nice.

**Comment by DCMattyG** [comment]
Hey @jeevanions, so glad you figured this out.

Yes, Admins can see ALL reservations, whereas non-admins will only see their own reservations.

Am I ok to close this issue? I believe you have what you need here.
