### ISSUE TITLE
Error in peering analysis, white screen

### ISSUE THREAD

**Issue by XtratusCloud** [Azure/ipam#111]
**Describe the bug**
The option Analysis -> Peering produces white screen, nothing is displayed.

**To Reproduce**
1. Go to 'Analysis.'
2. Click on 'Peerings'
3. White screen is displayed
4. See error in console "properties of undefined (reading 'color') at peering.js:521:39"

**Expected behavior**
The network and peerings graph should display normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/122672536/231495374-dc265c36-393e-48b7-b3a4-0efa405ef1bd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge 
 - Version: 112.0.1722.34

**Additional context**
Debugging in the browser I think the cause is that there is a peering with a different status than the expected (Connected, Disconnected, Updating).

Performing a KQL query I have found a peering in state "Initiated"
![image](https://user-images.githubusercontent.com/122672536/231495172-0faac6d1-9263-4912-8d8a-4a3c4261a627.png)

**Comment by DCMattyG** [comment]
As usual @XtratusCloud, this is an excellent find, thank you for the level of detail you provided!

Yes, this appears to be exactly the case that you highlighted above. I will add in another color case for "Initiated", as well as a default/fallback color so this won't happen again in the future.

I'll have a fix out this afternoon for you to test & verify before pushing the current branch to main.

**Comment by XtratusCloud** [comment]
I have tested the latest version in your working branch and the peerings are already shown correctly.
I'll wait for you to merge into main to deploy to production environment.

Thanks for the quick response ;)
