### ISSUE TITLE
Sudden Access Denied error shown to all admins and applications trying to access IPAM API

### ISSUE THREAD

**Issue by thelumlaa** [Azure/ipam#115]
### Discussed in https://github.com/Azure/ipam/discussions/114

<div type='discussions-op-text'>

<sup>Originally posted by **thelumlaa** April 13, 2023</sup>
All of a sudden all of my admins lost access to IPAM, including the API calls via Service Principal that was given access to the Engine App. I streamed logs and any request from any admin just leads to the following error

`2023-04-13T13:25:32.578523803Z Message: Please provide below info when asking for support: timestamp = 2023-04-13T13:25:15.3176720Z, correlationId = 
2023-04-13T13:25:32.578530703Z Exception Details:	(AccessDenied) Access is denied to the requested resource. The user might not have enough permission.
2023-04-13T13:25:32.578537403Z 	Code: AccessDenied`

We can sign-in through SSO, we all can see the admins list in the UI - and the list is not changed, we all are still set as admins - but any request to blocks/vnets/subnets/reservation just infinitely spins and outputs the error above in the logs.

I don't recall changing anything, the access worked last week. All the enterprise app credentials are valid, tried to restart the app but it doesn't help. Any idea what I can do to fix it?
Thanks</div>

**Comment by DCMattyG** [comment]
Good morning @thelumlaa, I'm so sorry you're having issues with your environment.

A quick note on how Users & Admins work in Azure IPAM....

When (non-admin) users login, their existing Azure AuthZ/AuthN are used, and their token is passed to the Engine and used as-is to query resources in Azure. When an admin user logs in, the engine uses the credentials assigned to the Engine App Registration to provide broader access to Networking constructs within your Tenant.

I explained the above to say that this would seem to be an issue with the App Registration/Service Principal for the Azure IPAM Engine. I would start by checking to see if the SP still has "Reader" at the Tenant Root Group (in Management Groups). If it has lost that permission, it won't be able to read Azure Resource Graph (hence Access Denied).

As I tell everyone, we are more than happy to meet 1:1 live to help you through some troubleshooting, so if you'd prefer that path drop me an email at Matthew.Garrett@microsoft.com and we can schedule some time.

++ @hbendana for visibility

**Comment by DCMattyG** [comment]
Hi there @thelumlaa, I see that you had marked #114 as "Answered", so I wanted to make sure that everything has indeed been resolved and you are now able to use the Azure IPAM product without any further issues.

If everything is in good working order, I'll close out this issue. Otherwise, please let me know how I may be of assistance to you so we can get you back up and running. Have a great one!

**Comment by thelumlaa** [comment]
Thanks @DCMattyG  - indeed, apparently there was a regional hiccup in Azure that day, it solved by itself automatically so let's close the issue

**Comment by DCMattyG** [comment]
Sounds great, have a wonderful rest of the week. We're always here to be of any further assistance!
