### ISSUE TITLE
The button 'Deploy to Azure' does nothing except opening a new tab displaying the 'Deploy to Azure' image

### ISSUE THREAD

**Issue by benoithamet** [Azure/ipam#12]
When hitting the 'Deploy to Azure' button the only thing happening is a new tab is opened which only display the 'Deploy to Azure' image

**Comment by DCMattyG** [comment]
Hey @benoithamet, at the moment there is no code or template within this repo that can be deployed. We are actively working on completing v1 of the IPAM solution, but the "Deploy to Azure" button is just a placeholder on the docs that we've been creating. I'll be sure to reach out once we complete our MvP as I'd love to get your feedback on the solution. Thank you so much for reaching out, and hopefully that button will be functional soon enough!
