### ISSUE TITLE
Unassigned vnet don't appears in block 'Virtual Network Association' option

### ISSUE THREAD

**Issue by XtratusCloud** [Azure/ipam#121]
**Describe the bug**
A network displayed in the vnet option as 'unassigned', cannot be associated to the appropriate block because it does not appear in the 'Virtual Network Association' list.

**To Reproduce**
1. Go to 'Discover' + 'vNets'
2. Search Unassigned vNets
3. Select one
4. Determinate the space & block by their cidr
5. Go to 'Configuration'
6. Select space and block
7. Click on ... + Virtual Networks
8. The unassigned vnet don't appears in the list.

**Expected behavior**
The unassigned vnet appears in the and allows to associate it

**Screenshots**
The vnet appears as unassigned
![image](https://user-images.githubusercontent.com/122672536/235138032-bf17e197-053c-40c4-86f4-efb7528d9504.png)

But don't appears in the block Virtual Networks
![image](https://user-images.githubusercontent.com/122672536/235138370-e0066b0a-6571-4b1e-b579-00e9cdcfbda6.png)

The vnet cidr (10.84.2.0/26) should be assignable to the block (10.84.0.0/15).

**Additional context**

**Comment by DCMattyG** [comment]
Hi @XtratusCloud, I believe I need some additional context.

At this point in time, a Virtual Network will not appear in the list in one of these two scenarios:
1. It's already associated to another Block within the same Space
2. There is an unfulfilled Reservation that overlaps this Virtual Network

The reason for 2 above is that by allowing a Virtual Network to be associated to a Block where an unfulfilled Reservation exists, once that Reservation is fulfilled, there will be IP overlap within the Block. This is why the behavior is currently not allowed.

Can you confirm in the situation described above that there are indeed no unfulfilled Reservations that overlap the range 10.48.2.0/26?

Thanks as always!

**Comment by XtratusCloud** [comment]
Hi @DCMattyG,
I will attempt to provide some additional information about the vnet. 
1. It is not associated with any block, and appears as <Unassigned> in the vnet list, as you can see. 
![image](https://user-images.githubusercontent.com/122672536/235897523-d92acef0-0fc1-4587-93ab-edc28143fbc1.png)
2. According to our configuration it could only be assignable to a single space and block, however I have searched for its id in database and it does not appear.
3. I have detected the issue because the vnet address range has been used for a new reservation, as the vnet is not associated to the block.

I have run the KQL query for vnets and appears, and I don't see anything strange on it values, and as expected it has no value in the column 'resv'.
![image](https://user-images.githubusercontent.com/122672536/235898784-f6767c47-ff00-4105-a106-5b7f5facc98f.png)

Let me know if I can help you by running any additional query or command.

**Comment by XtratusCloud** [comment]
Hi @DCMattyG ,

Following your indications, I have checked the active reservations.
You were right and there was an active reservation in the same range as the vnet.

I close the issue and thank you very much.
