### ISSUE TITLE
Suddenly blanc page and bad gateway 500 response trough API

### ISSUE THREAD

**Issue by Maurice-AxiansNL** [Azure/ipam#122]
From the rollout, I suddenly get a Bad Gateway error 500 through the API.

Then when I want to access the web app page through the Azure portal I get a blank blank screen. No error message or the like. 

Colleague has checked it and also in another environment the same issue. Did a web app restore from the backup of 1 month ago but that doesn't work either.

Is this problem known? Any idea how to troubleshoot this?

Thanks!

**Comment by Maurice-AxiansNL** [comment]
Apologies for not explaining it quite clearly.

The Azure IPAM has been running for several months and is now suddenly giving a blanc page and is not approachable via the API (Bad gateway error 500)

Thanks for the suggestions but those are about rolling out an IPAM webapp.

I use the API in other deployments to see what subnet is available for deploying a virtual network, and then I get the bad gateway error.

**Comment by DCMattyG** [comment]
Thanks for clarifying @Maurice-AxiansNL . Are you running Azure IPAM as a Function App then?

**Comment by Maurice-AxiansNL** [comment]
That is correct. 

App service with cosmosdb

**Comment by DCMattyG** [comment]
Got it @Maurice-AxiansNL, in that case my above recommendations around checking the Log Stream for any errors, and possibly downloading the runtime logs to see why the Function App isn't starting are the same. There has to be something that caused this issue, it could be an Azure Policy, or perhaps a permissions change.

The logs should tell us more and can be found here:

Function App -> Deployment Center -> Logs (tab)

From there we can find out what is causing the Function App to fail and return a 500 error.

**Comment by Maurice-AxiansNL** [comment]
I'm sorry, I think I'm a bit confusing with the term Function app in this case.

I deployed the Azure IPAM type "App Service" 

I attached a screenshot
![ntwipam01](https://user-images.githubusercontent.com/70941951/235614410-d26542af-e3be-4032-badc-cc020b8ee6d7.png)

**Comment by DCMattyG** [comment]
Gotcha @Maurice-AxiansNL! When you deployed this, did you use the ```deploy.ps1``` script that we provided, or did you deploy the Azure IPAM solution manually into Azure App Services?

If you did use the ```deploy.ps1``` script, then by default, it deploys the Web UI and Engine containers into an Azure App Service. In that case, my advice from above still stands true that we should examine the App Service logs for a cause of the failure.

I'm **more than** happy to meet with you 1:1 and personally help you through this issue. If you send me an email at Matthew.Garrett@microsoft.com and provide your time zone, I'll schedule something that is convenient for you, and together we'll get to the bottom of what is going on.

**Comment by Maurice-AxiansNL** [comment]
Thanks for offering your help. I am happy to take it up. Next 3 days I am abroad for work so let's plan something for next week.

Time zone is Amsterdam GMT+2

**Comment by DCMattyG** [comment]
Sounds great @Maurice-AxiansNL ! Please send me an email at Matthew.Garrett@microsoft.com so I can create a meeting invite for us next week. Talk to you soon.

**Comment by DCMattyG** [comment]
After working with @Maurice-AxiansNL, we found the issue was that the Managed Identity was somehow missing, causing authentication issues. After a redeploy, everything is back up and running!

Closing this issue, thanks so much!
