### ISSUE TITLE
Assign Managed Identity as an Admin or API user

### ISSUE THREAD

**Issue by CCHV-GitHub** [Azure/ipam#131]
I opened a discussion around how I might be able to achieve my goal, however I thought it might be worthwhile to open a feature request.

Can we allow Managed Identities to use the admin only API tools?

I have been trying to use an automation account managed identity to add VNETs to a Block, but the response i get is only admins can use this API, and it seems there is no way to add my managed identity to the admins list either, so I'm stuck.

**Comment by DCMattyG** [comment]
Hi @CCHV-GitHub, apologies for the delayed response, I'm actually OOO this week.

You can indeed add Managed Identities and Service principals as IPAM Admins. Though you cannot do this through the UI, you can do it via API.

Use a POST to `/api/admin/admins` like in the docs:

![image](https://github.com/Azure/ipam/assets/12955732/5034d060-1c3c-4e71-a923-4773d1f1cd0d)

Please remember that the ID is the **Object ID** of the Managed Identity. For the name & email you can choose whatever you'd like.

Hope that helps you out, please let me know if you have any issues implementing this!

**Comment by CCHV-GitHub** [comment]
Thanks for the info, i tried this earlier but it failed. Have just revisited and realised I forgot to put the content-type in the API call. Its working now, although I should have set myself as admin first, as now the only admin is the managed identity.

I can fix that one on my own though. Thanks for the help, you can close this now.
