### ISSUE TITLE
The Terraform module given for ip reservation is not idempotent

### ISSUE THREAD

**Issue by jeevanions** [Azure/ipam#137]
The example Terraform script provided is using a bash script that invokes reservation endpoint and it allocates new IP every time the Terraform is run. 

We constantly run the Terraform scripts and would like this to be idempotent. Is there a get existing IP reservation by tag so we can first query its existence and create a new one if it doesn't.

**Comment by DCMattyG** [comment]
Hi @jeevanions, there is another Azure IPAM customer whom created a proper Terraform provider. We worked closely with them on the creation and maintenance of this provider and you can find more details and usage examples here:

https://registry.terraform.io/providers/XtratusCloud/azureipam/latest/docs

We'll keep the very basic examples we have in the examples folder for now as some customers might want to use the script components of that for other processes, but you'll definitely want to use the official Azure IPAM Terraform provider by XtratusCloud for true idempotency.

Hope you enjoy!

**Comment by jeevanions** [comment]
Perfect. Thank you
