### ISSUE TITLE
IP Reservations with specified ip range

### ISSUE THREAD

**Issue by jeevanions** [Azure/ipam#144]
We are in the process of designing a migration strategy from our legacy internal IPAM solution to Azure IPAM. 

To Bring the existing IP Allocation retaining the IP Range to the New system we wonder if it is possible to specify the IP Range where the IPAM automatically does the reservation irrespective of the space and block. 

Our existing interface was dynamic and it takes region and size as parameters, Then carves out a subnet from the available CIDR pools. 

The IP range was used to create VNet and our team would need to retain the IP as it would disrupt their infrastructure.

**Comment by jeevanions** [comment]
We use Terraform and there are multiple teams use the Terraform module we provide. The existing IP Reservation is stored in the State and now we need to migrate it without changing the IP Range (IP reservation). Changing the IP would cause the whole Terraform resources to re-create.

**Comment by DCMattyG** [comment]
Thanks for the clarity @jeevanions!

I'm actually working on something similar with another customer...would you ideal workflow look something like this?

![image](https://github.com/Azure/ipam/assets/12955732/7fc3c1b1-4340-46bc-bbb6-45e7dc0a1367)

Please keep in mind, this is targeted at Subnets, but we could also do something like this for Virtual Networks if needed.

Let me know what you think 😉

**Comment by jeevanions** [comment]
We are using the IP Reservation for the VNet. Our Migration Mapping looks like this.

![Screenshot 2023-07-18 at 16 50 35](https://github.com/Azure/ipam/assets/95138087/eb9d8996-8dd5-41f0-9e1a-60b18dcf2e80)

**Comment by michael-brown-22** [comment]
@DCMattyG I have another use case where this could be useful. 

We are in the process of developing an Azure Landing Zone using the CAF module and we are building out the LZ then installing Azure IPAM into the LZ management area. 

As a result our connectivity Hub is already in place but because we didn't request the reservation (although can add it via the UI as a network) we wouldn't have the tag value. 

We are planning to have a policy which audits virtual networks that do not have that tag present to highlight where people may have followed the incorrect process or manually created resources.

**Comment by DCMattyG** [comment]
Hey @jeevanions, you might want to check out Issue #190 and PR #202. You are now able to specify a CIDR when creating a **Reservation**.

I think this addresses your original ask from the top of this thread, but please take a look and let me know. Thanks!

**Comment by DCMattyG** [comment]
Good afternoon @jeevanions, wanted to check and see if you ever had a chance to explore the latest API changes I had mentioned above and if those updates addressed this particular issue for you. If not I'm always happy to have a quick call to better understand what gaps we have, and how best we can address them for you moving forward.

Thank you much!

**Comment by DCMattyG** [comment]
Hi @jeevanions, I wanted to check one more time to see if you've had a chance to use the updated Reservations API where you can now specify a CIDR that you want as opposed to just having a new CIDR generated each time.

I hope that meets you're needs and it's working as you expect. If there are any issues or adjustments you'd like make, just let us know and we'll work to get you taken care of right away.

Thank you, really appreciate your feedback and suggestions!

**Comment by DCMattyG** [comment]
Good evening @jeevanions, I have reached out a few times over the last few months to check on this issue. As I haven't heard back from you in a while, I'm going to close this issue for now. If for any reason the API updates I had mentioned above haven't addressed your issue or you still have some open questions on this topic, please don't hesitate to re-open this issue or reach out to me directly.

Hope all is well and thank you as always for reaching out for support!
