### ISSUE TITLE
Error 500 Network Associations

### ISSUE THREAD

**Issue by positivism1** [Azure/ipam#159]
**Describe the bug**
Using the API to associate a Network to a Block - error Internal Server Error 

**To Reproduce**
Associate a virtual network to a block via the API
![image](https://github.com/Azure/ipam/assets/3076159/5a733e32-3805-49a3-8bab-c6f9d95af82a)

![image](https://github.com/Azure/ipam/assets/3076159/d0b16e12-93dc-4cde-8bc8-720e58961107)

**Comment by DCMattyG** [comment]
Thanks for bringing this to my attention @positivism1 . I've found the issue and will have a fix pushed out for it in the morning along with instructions on how to update the images in your Private ACR.

**Comment by DCMattyG** [comment]
Ok @positivism1, I believe this should now be resolved with #161. Please pull the latest code from **main** and then push a new version of the Engine container to your Private ACR using the below process:

https://azure.github.io/ipam/#/contributing/README?id=building-production-containers-images-using-a-private-acr

Please let me know if you have any issues, hopefully this resolves the issue for you!

**Comment by positivism1** [comment]
Thanks! It's working now. 👏

**Comment by DCMattyG** [comment]
Great to hear, thanks for the great teamwork!
