### ISSUE TITLE
Are there any way to check the availability of a certain CIDR range via using API

### ISSUE THREAD

**Issue by trandangtri** [Azure/ipam#166]
Let say I wanna allocate a subnet from within a certain CIDR range, from my administration application, via using API request. I just wanna make sure this CIDR range is available and not overlapped with others.

At this moment, can I do that with API request, to IPAM engine?

**Comment by DCMattyG** [comment]
Hi @trandangtri, this is an excellent use case!

Just to be clear, we're talking about checking if a CIDR is in use withing a specific Space/Block, correct?

Whould an API like this make sense:
**/api/spaces/ExampleSpace/blocks/ExampleBlock/cidrCheck**

Or perhaps this might fit better under the **Tools** section:
**/api/tools/cidrCheck**

What are your thoughts here?

**Comment by tritranmck** [comment]
Hi @DCMattyG 

Thanks for your response. Meant, we didn't support this function at this moment yet?
In that case, did you know are there any way to work around?
Highly appreciated

**Comment by trandangtri** [comment]
Hi @DCMattyG 

Thanks for your response. Meant, we didn't support this function at this moment yet?
In that case, did you know are there any way to work around? Highly appreciated

**Comment by DCMattyG** [comment]
Hey @trandangtri, there's not workaround within the product today, but perhaps you could do some calculations using something like the **netaddr** library in Python. Not sure what environment you're using here.

I can get this feature added in fairly quickly. I'm finishing up some major updates this week, so I can likely have this done by the end of this month. Did you have a preference on how this API should be presented (from my comment [above](https://github.com/Azure/ipam/issues/166#issuecomment-1708635007))?

**Comment by trandangtri** [comment]
Hi @DCMattyG . That sounds great, thanks for support.

In general speaking, I prefer option #2, where I don't need to specify Space and Block as required. If I want to, I could do that with arguments.
 
`/api/tools/cidrCheck`

Regards

**Comment by DCMattyG** [comment]
I'm on it @trandangtri!

I'll begin working on this right away 👍

**Comment by DCMattyG** [comment]
Good afternoon @trandangtri, I wanted to run this by you...

Given an input CIDR of something like "10.1.0.0/16", would a response like the following make sense:

```
[
  {
    "name": "Test-vNET",
    "id": "/subscriptions/13599e70-8675-4012-ba4d-7508a8b9fd1e/resourceGroups/RG-TESTING/providers/Microsoft.Network/virtualNetworks/Test-vNET",
    "resource_group": "rg-testing",
    "subscription_id": "13599e70-8675-4012-ba4d-7508a8b9fd1e",
    "tenant_id": "9a885645-7e98-4479-8ae3-4118e0c13594",
    "prefixes": [
      "10.1.0.0/24"
    ],
    "containers": []
  },
  {
    "name": "Services-vNET",
    "id": "/subscriptions/57ff49dd-d5b5-48cb-b920-c5f0593c7f5b/resourceGroups/RG-SERVICES/providers/Microsoft.Network/virtualNetworks/Services-vNET",
    "resource_group": "rg-services",
    "subscription_id": "57ff49dd-d5b5-48cb-b920-c5f0593c7f5b",
    "tenant_id": "9a885645-7e98-4479-8ae3-4118e0c13594",
    "prefixes": [
      "10.1.0.0/16"
    ],
    "containers": [
      "/spaces/TestSpace/blocks/TestBlock"
    ]
  },
  {
    "name": "Marketing-vNET",
    "id": "/subscriptions/4bf4a48d-aa55-4c03-b575-fb612f52a218/resourceGroups/RG-MARKETING/providers/Microsoft.Network/virtualNetworks/Marketing-vNET",
    "resource_group": "rg-marketing",
    "subscription_id": "4bf4a48d-aa55-4c03-b575-fb612f52a218",
    "tenant_id": "9a885645-7e98-4479-8ae3-4118e0c13594",
    "prefixes": [
      "10.1.0.0/16"
    ],
    "containers": []
  }
] 
```

You can see here it would show you all overlapping vNET's, and call out the ones that are container within existing Spaces/Blocks if such an association exists.

Is this what you are looking for?

**Comment by trandangtri** [comment]
Such wonderful. Although my initialized thought is to check the availability of a certain CIDR range, but in case we are able to dive deeper into the existing ranges like your response example, I would love to have a distinct container info:
 
```json
[
  {
    "name": "Services-vNET",
    "id": "/subscriptions/57ff49dd-d5b5-48cb-b920-c5f0593c7f5b/resourceGroups/RG-SERVICES/providers/Microsoft.Network/virtualNetworks/Services-vNET",
    "resource_group": "rg-services",
    "subscription_id": "57ff49dd-d5b5-48cb-b920-c5f0593c7f5b",
    "tenant_id": "9a885645-7e98-4479-8ae3-4118e0c13594",
    "prefixes": [
      "10.1.0.0/16"
    ],
    "containers": [
      {
        "space": "TestSpace",
        "block": "TestBlock"
      }
    ]
  }
]
```
Then, I don't need to work on string parsing anymore, if I need to retrieve further information. Just my 2 cents

**Comment by DCMattyG** [comment]
Hi @trandangtri, I've implemented this new API in the latest code changes from PR #181. Please restart your IPAM App Service to pull down the latest containers for testing.

![image](https://github.com/Azure/ipam/assets/12955732/435f188c-3b48-4b8e-a30f-ea4fbf4ce32d)

Here's the details from the API Docs page:

![image](https://github.com/Azure/ipam/assets/12955732/22225a95-0f10-4d59-a176-c6a5fb670de9)

Please give it a test and let me know if it meets all of your expectations. Thanks so much!

**Comment by DCMattyG** [comment]
Good morning @trandangtri, just wanted to check-in with you on this item. Please let me know once you've had a chance to test everything out and have verified that the new API (above) meets your requirements.

Much appreciated!

**Comment by DCMattyG** [comment]
Hi @trandangtri, I know it's been a while but I wanted to see if you've had a chance to test out this functionality and are satisfied with the implementation.

Let me know when you can, thanks so much!

**Comment by DCMattyG** [comment]
Good afternoon @trandangtri, I'm circling back one last time before closing out this issue. Have you been able to test everything out, and if so is everything looking good or perhaps is there anything we need to tweak about this solution?

Appreciate the feedback!

**Comment by DCMattyG** [comment]
Hey there @trandangtri, as this item has been addressed for quite some time now, I'm going to close this issue for the time being. If for any reason you aren't satisfied with the provided fix, please feel free to either re-open this issue or file a new one, and I'll make sure we get everything working as you expected.

Thanks for the contribution, and know we're always here if there's anything else you ever need. Thank you!
