### ISSUE TITLE
Cannot rename block to the same name but in lower cases

### ISSUE THREAD

**Issue by cata008** [Azure/ipam#172]
**Describe the bug**
When I try to edit the name of a block it wouldn't let me use the same name in lower cases.
Choosing a temp name and later using the intial one in lower cases does the trick.

**Expected behavior**
Be able to rename the block with the original name in lower cases.

**Screenshots**
<img width="609" alt="image" src="https://github.com/Azure/ipam/assets/37331541/d795fa31-45ff-45f7-813e-37df3fa12a8e">

**Comment by DCMattyG** [comment]
Thanks for bringing this to my attention @cata008, I'll starting working on a fix for this right away!

**Comment by DCMattyG** [comment]
Hi @cata008, this should be fixed now with PR #181, please restart your IPAM App Service to pull down the latest containers.

![image](https://github.com/Azure/ipam/assets/12955732/435f188c-3b48-4b8e-a30f-ea4fbf4ce32d)

Please let me know if everything looks good and we can close out this issue, thanks!

**Comment by cata008** [comment]
Hi @DCMattyG. Thanks for fixing this!

**Comment by DCMattyG** [comment]
You're welcome, closing this issue now that this has been addressed.
