### ISSUE TITLE
Blocks - Network associations - Page loading multiple times

### ISSUE THREAD

**Issue by cata008** [Azure/ipam#174]
**Describe the bug**
While trying to associate new vnets to an existing block, the page is loading the results again which results in having to repeat the same steps all over.

**To Reproduce**
Blocks - Network associations - Wait for the page to be loaded with all vnets - Select networks to be associated - The page is reloading again after scrolling down and looking to select more networks losing all progress already made

**Expected behavior**
Blocks - Network associations - Wait for the page to be loaded - Select networks to be associated - Save

**Screenshots**
<img width="475" alt="image" src="https://github.com/Azure/ipam/assets/37331541/56f107de-b22e-41c7-9dfe-b0fc68b3ea22">

**Comment by DCMattyG** [comment]
Thanks for bringing this to my attention @cata008, it on my list to get fixed ASAP 👍

**Comment by DCMattyG** [comment]
Hi @cata008, this should be fixed now with PR #181, please restart your IPAM App Service to pull down the latest containers.

![image](https://github.com/Azure/ipam/assets/12955732/435f188c-3b48-4b8e-a30f-ea4fbf4ce32d)

Please let me know if everything looks good and we can close out this issue, thanks!

**Comment by cata008** [comment]
Hi @DCMattyG. The behavior is not the same anymore, however, the fix seems to have introduced another issue. When selecting the block and checking the "Block Networks", it seems that the associations are not loaded anymore. In order to be able to see them, the config page has to be reloaded.

**Comment by DCMattyG** [comment]
Ok @cata008, I think I've got this fixed not in #185. Please restart your Azure IPAM App Service once again and verify that the behavior is now as expected. Thanks so much!

**Comment by cata008** [comment]
@DCMattyG, thanks! Seems solved indeed.

**Comment by DCMattyG** [comment]
Great to hear @cata008, thanks for working so closely with me on this!

Closing this issue now as it appears to be resolved.
