### ISSUE TITLE
External networks - Page saving issue

### ISSUE THREAD

**Issue by cata008** [Azure/ipam#179]
**Describe the bug**
When saving external networks on an existing block, the page becomes blank. In order to continue adding more external networks, one needs to go back to the IPAM UI URL and repeat the same steps to get to the config screen.

<img width="591" alt="image" src="https://github.com/Azure/ipam/assets/37331541/522366a1-7da5-4f77-8d33-6d311d47e927">
<img width="405" alt="image" src="https://github.com/Azure/ipam/assets/37331541/9450329d-5b3c-46e7-bc30-5ac09abca6c9">

**Expected behavior**
Save the entries and go back to the config page.

**Additional info**
The external networks that were associated with the block are actually saved.

**Comment by DCMattyG** [comment]
Hi @cata008, is this happening after every time you save the changes?

**Comment by cata008** [comment]
@

> Hi @cata008, is this happening after every time you save the changes?

Yes, correct.

**Comment by DCMattyG** [comment]
Ok, thanks for the details. Looking into it now!

**Comment by DCMattyG** [comment]
Ok @cata008, I've located the bug and will work on pushing out a fix ASAP. Great catch on this one!

**Comment by DCMattyG** [comment]
Hi @cata008, this should be fixed now with PR #181, please restart your IPAM App Service to pull down the latest containers.

![image](https://github.com/Azure/ipam/assets/12955732/435f188c-3b48-4b8e-a30f-ea4fbf4ce32d)

Please let me know if everything looks good and we can close out this issue, thanks!

**Comment by cata008** [comment]
Hi @DCMattyG. Thanks for fixing this!

**Comment by DCMattyG** [comment]
You're welcome, closing this issue now that this has been addressed.
