### ISSUE TITLE
Unable to manage SPN Permissions since Pydanticv2 Upgrade

### ISSUE THREAD

**Issue by ChrisSidebotham** [Azure/ipam#187]
Using the API to manage permissions in a pipeline requires the use of a service principal. However since the upgrade to PydanticV2 (my only correlation) this is now erroring with 'Internal Server Error'

### Portal behaviour:
Using a Admin User Account, attempt to add service principal as admin = 422 Error received 
``` json
{
    "detail": [
        {
            "type": "value_error",
            "loc": [
                "body",
                3
            ],
            "msg": "Value error, email should not be set for 'principal' type",
            "input": {
                "type": "Principal",
                "name": "REDACTED",
                "id": "REDACTED",
                "email": null
            },
            "ctx": {
                "error": {}
            },
            "url": "https://errors.pydantic.dev/2.4/v/value_error"
        }
    ]
}
```
- Viewing the Log Stream within the application the following error is visable:
`2023-10-10T10:55:37.878872401Z   {'type': 'value_error', 'loc': ('response', 1), 'msg': "Value error, email should not be set for 'principal' type", 'input': {'type': 'Principal', 'name': 'REDACTED', 'email': None, 'id': 'REDACTED'}, 'ctx': {'error': ValueError("email should not be set for 'principal' type")}, 'url': 'https://errors.pydantic.dev/2.4/v/value_error'}`

### API Behaviour (using postman as SwaggerUI is missing auth headers)
- As Admin - add SPN user POST /admin/admins - postman returns no response body
- Run Get /admin/admins with user account and internal Server Error is shown:
![image](https://github.com/Azure/ipam/assets/48600046/02c9b0b6-1a3a-4a02-bc8a-60bfaa2ecfd8)
- Remove Admin using Delete /admin/admins/{objectId}
- Run Get /admin/admins again and response succeeds:
```json
[
    {
        "type": "User",
        "name": "Chris",
        "email": "REDACTED",
        "id": "REDACTED"
    },
    {
        "type": "User",
        "name": "Chris(UK Dev)",
        "email": "REDACTED",
        "id": "REDACTED"
    },
    {
        "type": "User",
        "name": "Barry",
        "email": "REDACTED",
        "id": "REDACTED"
    }
]
```

**Comment by ChrisSidebotham** [comment]
Great work @DCMattyG

**Comment by DCMattyG** [comment]
Thanks for all of the helpful details above @ChrisSidebotham and the chat on Teams. Definitely helped to get this fixed ASAP!
