### ISSUE TITLE
I would like to reserve IP Address on My Own from the given block

### ISSUE THREAD

**Issue by shoebece** [Azure/ipam#190]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex.  Currently the Ipam reserves the IP Address from the given block in the random fashion. However we have a requirement to assign unique different cidr ranges to different businesse units but we have common block of 10.0.0.0/8

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shoebece** [comment]
Hello DCMatty,

Apologies for the late reply.

We have created a block "10.0.0.0/8" and we are using IPAM terraform
provider to create reservation and block as part of VNET creation. example:
currently its reservering the IP address in a sequential order like it
books 10.0.1.0/24 in a first iteration and in the second iteration
10.0.2.0/24

However, sometimes we get a requirement as such - we have to choose the IP
range on our own like example: 10.0.64.0/24. and our expectation is in some
way we provide this ip range to the IPAM tool - if the range is available
it should reserve it.

you are right --

Does it mean that, for example, 10.0.0.0/16 is for "business unit 1" and
10.0.1.0/16 is for "business unit 2"?

yes

Does it mean you want to reserve a very specific CIDR such as "10.0.100.0/24"
no matter what, you just want to specify the range for which to be reserved?

yes

**Comment by DCMattyG** [comment]
Thank you so much for the feedback @shoebece! This makes perfect sense, so I'm happy to get to work on this for you.

Out of curiosity, is there a reason you don't break up the Block into smaller Blocks to better represent the different business units (e.g. Block01 w/ CIDR of 10.0.0.0/16 is for "business unit 1" and Block02 w/ CIDR of 10.0.1.0/16 is for "business unit 2")? Just a side though you might consider as well to better organize things within the IPAM tool 😉

**Comment by shoebece** [comment]
Thanks a lot for your reply, I completely understand that in an Ideal world
we should have multiple blocks, however being this very dynamic in nature
as our company continues to acquire businesses across the world and also we
have integrated Azure IPAM  in our common IAC terraform pipelines.

Currently in scenarios where it's an extension to existing business, we
know what IP range we have to use.

However, as IPAM blocks IP on its own. We are creating VNET manually
without IPAM and blocking in IPAM.

So I was looking, if we give some ip range to "Azure IPAM" - if available
it should block it.

Many thanks for sharing your expertise and consideration.

**Comment by shoebece** [comment]
Dear,

You are a magician - Many thanks for a quick turnaround.

It is working as expected on my side.

I could not thank you enough for this new feature.

**Comment by DCMattyG** [comment]
Great to hear @shoebece, always happy to help bring new & useful features to the platform.

Please let us know if you need anything else in the future!

**Comment by shoebece** [comment]
Thank you and I will.
