### ISSUE TITLE
Health Check status page

### ISSUE THREAD

**Issue by michael-brown-22** [Azure/ipam#191]
**Is your feature request related to a problem? Please describe.**
No additional feature request.

**Describe the solution you'd like**
The addition of a /health page endpoint could be useful to allow the monitoring of the service. This could then be configured as part of the application service. In our use case we would be required to be notified and react to the application if it goes down.

**Comment by DCMattyG** [comment]
Good morning @michael-brown-22, what type of information are you looking for on a status page?

Are you just looking for it to return "something" to show that the service is up and running?
Are there any specific details that this page needs to return?
Given that there are multiple containers, where should the "/health" endpoint live? Engine? UI? All of the above?

I just need a bit more information on how you'd like to see this endpoint function and then we can talk more about next steps.

Thanks much!

**Comment by michael-brown-22** [comment]
If I have understood the documentation on the [app service health check](https://learn.microsoft.com/en-us/azure/app-service/monitor-instances-health-check) it will check all 3 nginx/engine/ui (although I can't find anything explicit on the this with the use of docker compose as the container type).

I suspect that it will route to the endpoint https://<app_service_url>/health and the requirement would be to return a http response code. 

If I had to select where the health check endpoint lived I would say part of the engine as the functionality would still be there via the API even if UI failed. It would also inherently verify that nginx is functioning by the fact its providing a response or fails due to timeout.

**Comment by DCMattyG** [comment]
Understood. I'm going to park this until the end of the month as I'm currently working on collapsing all of the containers into either:

1. No container at all, native App Service code
2. A single container

I can easily add a more functional "/health" endpoint at that time that will be much for meaningful. ETA on these updates is the end of the month.

**Comment by DCMattyG** [comment]
Hey @michael-brown-22, this is now complete with #230 and you can reach the status page by navigating to `/api/status` after pulling down the new containers (by restarting your Azure App Service).

The returned status message will become more detailed over time, but I believe this is a great start and should be exactly what you were looking for.

Please reach out with any additional questions and I'll be happy to address them for you!
