### ISSUE TITLE
IP Planner Tool does not display the available ranges /28 - /30 correctly

### ISSUE THREAD

**Issue by pschonfeld** [Azure/ipam#193]
**Description**
If I use the "Planner" tool in the Tools -> Planner tab and select any Virtual Network, the address ranges with the mask /28 - /30 do not correctly display the number of available ranges. For example, my vNET has a range of /20 (i.e., 4096 IP addresses). The/28 range in the planner shows "MASK: 28 | (1/16 Used)". But I can create up to 256 subnets in Azure, not 16. The same problem then continues for ranges /29 and 30.

**Screenshot**

![image](https://github.com/Azure/ipam/assets/7692895/ad3445b4-11e4-45ad-8c7e-c7a34818c5b4)

**Comment by DCMattyG** [comment]
Hi @petrschonfeld, I'll start working on a fix for this right away. Thanks for bringing this to my attention!

**Comment by DCMattyG** [comment]
Hi there @petrschonfeld, this should no be addressed in #201. Please restart your Azure IPAM App Service, allow it to pull the updated containers, and give it a test for me.

I wrote some automation to test various CIDR's against the IP Planner code, so I should be able to troubleshoot these things much faster in the future.

Have a great one!

**Comment by petrschonfeld** [comment]
Hi @DCMattyG, thanks for a pretty much quick fix. It works like a charm. 👍

**Comment by DCMattyG** [comment]
Wonderful to hear, so happy we could get that fixed quickly for you!

**Comment by DCMattyG** [comment]
Hi @pschonfeld, apologies for the delayed response on this...

I've re-written the Planner code from scratch to address this issue. The next release will include all of the fixes and I'll make sure to ping you once that code is available. Really appreciate you flagging these bugs and helping us make the product even better!

**Comment by DCMattyG** [comment]
Hey there @pschonfeld, I've completely re-written the planner code and with #230 this should now be fixed (hopefully forever)!

If you've used the standard deployment script you can simply restart you Azure App Service and it will pull the latest containers down which contain the fixes.

Please let me know how everything is looking now!

**Comment by DCMattyG** [comment]
Good afternoon @pschonfeld, just checking in that the fix got you where you need to be. Please let me know if were good to close this issue out (again).

Thanks so much!

**Comment by DCMattyG** [comment]
Hi @pschonfeld, as this bug has been fixed for quite some time and I haven't heard back from you, I'm going to close this issue for the time being.

If for any reason you're still having issues with this, please feel free to re-open this issue or file a new one and I'll make sure you get taken care of right away.

Thanks so much for reporting this and I hope all is working much better for you now!
