### ISSUE TITLE
Releases and versioning

### ISSUE THREAD

**Issue by StefanIvemo** [Azure/ipam#227]
**Is your feature request related to a problem? Please describe.**
At the moment it's hard to track changes made in the IPAM tool. There are no release notes and I can't see which version of the IPAM I'm running at the moment. 

**Describe the solution you'd like**
Start working with releases in the repository and write release notes that clearly shows what features have been added, bug fixes implemented and possible breaking changes. Along with this it would be great if the version number becomes visible in the UI. 

**Describe alternatives you've considered**
N/A

**Additional context**
I've seen this raised in the discussions as well. But I'm adding it here since I believe that it's important to get this in-place.

**Comment by DCMattyG** [comment]
Hi @StefanIvemo, I've actually been working on this for a while now and I'm happy to say this item is now complete!

Starting in #230, I've added some GitHub Action workflows that will create a versioned Release with every PR merge. I'll be improving this flow over time (including better details in the release notes), but at least we have the first steps in place.

Additionally, you can now use the status API at `/api/status` to see what version you are running, and this will bubble into the UI shortly.

Thanks for reaching out and the wonderful suggestion. Don't hesitate to let us know if you need anything else!
