### ISSUE TITLE
Add next available vNet CIDR to GUI

### ISSUE THREAD

**Issue by bordera-randy** [Azure/ipam#228]
Add a way for someone to login to the GUI and find the next available CIDR to be used for a new vNet. 
This will allow for planning and new vnets to be created in instances where the API  is either not readily available (ie user is not familiar with the API)

similar to the Planner tool but for vnets 

being able to create a reservation from this would also be helpful if the X-IPAM-RES-ID would be exposed so the Azure tag can be created to link to the reservation. 

@DCMattyG  this is the one we spoke about on the call today.

**Comment by DCMattyG** [comment]
Hi @bordera-randy, acknowledging this and now that **v3.0.0** is fully released, I'm hoping to have something for you shortly to test on this item.

Thanks for the excellent Teams conversation, looking forward to working with you on this ask!

**Comment by bordera-randy** [comment]
@DCMattyG 
was there an update on this?

**Comment by DCMattyG** [comment]
Hi @bordera-randy, I'm nearly complete with this as requested. Would you have some time in the next few days to have a quick Teams call so I can demonstrate the new functionality and get your feedback?

**Comment by bordera-randy** [comment]
@DCMattyG 
Yes please let me know  your availability or just email me

**Comment by DCMattyG** [comment]
Hi @bordera-randy, this feature is now fully incorporated into the latest release (v3.2.0). Please let me know if you have any questions/comments/concerns and I'll be happy to address them immediately.

Thanks so much!

**Comment by DCMattyG** [comment]
Hi @bordera-randy, given that this functionality had been available for several months now, I'm going to close this issue. If for any reason things aren't working as expected or you need any additional support on this topic, please don't hesitate to re-open this issue or reach out to me directly.

Hope you're enjoying Azure IPAM, and we'll be here if you need anything else in the future. Thanks!
