### ISSUE TITLE
Reservations for External networks

### ISSUE THREAD

**Issue by luisarnauth** [Azure/ipam#249]
**Is your feature request related to a problem? Please describe.**
Yes, the problem arises when working with multiple cloud providers that use different IPAM solutions. This can become a challenge, especially for organizations that do not have a dedicated IPAM solution. The Azure IPAM solution has been a valuable tool for documenting external networks. However, it currently lacks the ability to request a reservation for these external networks.

**Describe the solution you'd like**
I propose the addition of a feature that allows users to request IP reservations for external networks directly within the Azure IPAM solution. This feature would greatly enhance the functionality of the Azure IPAM solution and streamline the process of managing IP addresses across multiple cloud providers.
It could be as simple as providing a reservation flag for external networks. In the event of the reservation being for an external network, it would be marked it as "fulfilled" and possibly settled.

**Describe alternatives you've considered**
I've tried the following workaround:
1. Create a reservation to get both the address space as its ID.
2. Delete the reservation using the ID.
3. Create an external network using the provided address space from step 1

Unfortunately, the reservation gets marked as "cancelledByUser" and when trying to assign the external network the same address space as the reservation there's a 400 error:  "Block contains unfulfilled reservation(s) which overlap the target external network.".

**Comment by DCMattyG** [comment]
Good morning @luisarnauth, and thank you for a wonderful suggestion.

The good news is that I'm literally working on something very similar as we speak for another customer. Would you like me to reach out for you when the test code is ready so that you can provide some feedback before it goes GA?

**Comment by luisarnauth** [comment]
Sure, I'm available to test it against my use case and help you out on others

**Comment by DCMattyG** [comment]
Excellent! If you'd like to have a quick sync call to see the plan of what I'm building, please feel free to drop me an email at Matthew.Garrett@microsoft.com and we can schedule 10/15 minutes to make sure this will meet all of your needs.

**Comment by DCMattyG** [comment]
Hi @luisarnauth, thanks for the live conversation on Teams. I believe we are aligned that the current updates I'm already working on should meet your needs here.

I'm estimating to be complete with the changes by the end of the month. Thank for your patience, I'll reach out once everything is ready for your feedback and approval.

Have a good one!

**Comment by DCMattyG** [comment]
Hi @luisarnauth, all of the new managed external network features have been incorporated into the latest release (v3.2.0) which were brought in from PR #279.

I hope everything is working to your expectations, please let me know if you have any questions/comments/concerns.

Thanks so much!
