### ISSUE TITLE
Support setting up IPAM at management groups other than the tenant root

### ISSUE THREAD

**Issue by harsimranmaan** [Azure/ipam#261]
**Is your feature request related to a problem? Please describe.**
I am interested in deploying the solution a specific management group instead of the Tenant Root
**Describe the solution you'd like**

It should be possible to restrict the IPAM solution to a specific management group and its children. Multiple IPAM instances can be deployed based on organizational use cases within a tenant.

It should be possible to specify an additional attribute `MANAGEMENT_GROUP_ID` to the config and use it for looking up networking details. The `TENANT_ID` would still be needed for auth token verification.

**Describe alternatives you've considered**
Install IPAM with Reader access to Tenant Root

**Additional context**
Grant Reader access at the Tenant Root is not a desired option

**Comment by DCMattyG** [comment]
Hi @harsimranmaan, this is a fair ask an other have made it too. This is on the near-term roadmap so it should be available in the deployment script soon.

In the meantime you can simply add the IPAM Engine Service Principal as a Reader on the target Management Group, then remove it from the Root Management Group as a workaround.

I'll update this issue and link it to the PR once we've added this option to the deployment script. Thanks so much for reaching out and the great suggestion!

**Comment by DCMattyG** [comment]
Hey there @harsimranmaan, this option is now available in the latest release (v3.2.0) which came from PR #279. You can find the additional switch in the deployment docs [here](https://azure.github.io/ipam/#/deployment/README?id=full-deployment).

Hope everything is working as you expect, please let me know if you have any issues!

**Comment by DCMattyG** [comment]
Hi @harsimranmaan, I'm going to close this issue as the fix has been available for several months now. If you are still having issues with this, please don't hesitate to re-open this issue or reach out to me directly.

I hope the new functionality is working to your satisfaction!
