### ISSUE TITLE
block reservation with 2 vnets

### ISSUE THREAD

**Issue by stumueller** [Azure/ipam#266]
**Describe the bug**
Not sure if this should be a bug or feature request.

I have a block called 10.227.32.0_20 with a CIDR of (you guessed it) 10.227.32.0/20
I have created a reservation for this block.
I have now created two vnets with address spaces
10.227.32.0/21
and
10.227.40.0/21
However when I fill out the reservation tag on the first vnet looing at the reservation on hte block warns me that the address spaces doesn't match the reservation. And I don't see the vnet associated with a block on the discover tab.
I also see nothing when I click on select the block, click the 3 ellipses and choose block network

I would like to reserve an entire block and create as many vnets within that block as I need.

**Comment by DCMattyG** [comment]
Good morning @stumueller, I do understand your ask but the way that the product is currently designed is there should be one Reservation per Virtual Network Address Space.

For your above example, you can simply create two Reservations, which will in-turn provide you with two Tags that you can apply to the respective Virtual Network upon creation and then the Azure IPAM tool can match up the newly created Virtual Networks to those Reservations.

I hope that makes sense, but Reservations were never designed to be ambiguous. That said, you can use multiple Reservations to create multiple Virtual Networks and you can also use multiple Reservations to apply multiple Address Spaces on a single Virtual Network as well.

I hope that helps better explain the relationships of Reservations to Virtual Networks.

**Comment by stumueller** [comment]
So a reservation is tied to a vnet not to a block.
In my case I could assign a reservation to a block until such time as the dev team have identified the number of vnets and then delete the reservation and recreate the correct reservations

**Comment by DCMattyG** [comment]
Yes that is one way of doing it, but I'd ask the question why it was important to place a hold on the IP Space *before* the number of Virtual Networks is known.

May I ask why the Reservations can't be created at a later point in the process?

**Comment by stumueller** [comment]
we have a number of development teams who are responsible for their own infrastructure and networking, however due to us needing services to communicate we need to introduce peering between the networks, as such we don't want teams to just go off and create whatever address spaces they feel like.
We have split our ip range into a number of address spaces, which I am adding as blocks. the idea is that each team will pick a block and reserve it so that other teams can't use it. they will then identify how many vnets within that block they need ad create them accordingly.

I guess the reservations could be created once the teams have identified the needed vnets, im just trying to be extra careful that we dont end up with two teams accidentally picking the same block. And I thought if I add a reservation to a block it doesn't matter how long it takes a team to identify their needed vnets

**Comment by DCMattyG** [comment]
That a great point @stumueller, and I think you're highlighting some of the **exact** reasons this tool exists.

As long as all of the teams are requesting IP space via the IPAM tool, it will never dish out overlapping IP space. That way you can have peace of mind that your teams are enabled for self-service (if you so desire) and that only unique IP ranges will be given during each Reservation request.

If you'd like, I'm happy to talk through your IPAM strategy and provide a point of view. I can always be reached at Matthew.Garrett@microsoft.com and I'm happy to setup some time for us to chat 1:1 during a time that is convenient for you.

**Comment by DCMattyG** [comment]
Hi @stumueller, I just wanted to check and see if you still have any remaining questions on this topic after our 1:1 session a while back. I hope everything is a bit more clear now as to how the product is intended to work and some ideas as to the best way for you to incorporate it into your existing business flows.

If you need anything else, I'm happy to meet as many times as you need to feel comfortable and to make sure all of your questions are answered.

Have a great one and hope you're enjoying Azure IPAM!

**Comment by stumueller** [comment]
Hi

Thanks for following up. I don't have any more questions at this point. I've showed the work flow and tool to my head of service and they are happy with it. So I'm just working on implementing it now. 

If any thing comes up when we actually start to use it I'll let you know

**Comment by DCMattyG** [comment]
Closing this as complete per notes above. Thanks so much for reaching out, we're always here to help!
