### ISSUE TITLE
Block filter in VNETS page is case sensitive

### ISSUE THREAD

**Issue by fqzy826** [Azure/ipam#268]
**Describe the bug**
The Block filter in the VNETS page is case sensitive, but in the BLOCKS page, it is not.

For example, I have a block name "Hub-Core"
In the BLOCKS page, under "Block Name" filter, I type "core", it return result
In the VNETS page, under "Block", I have to type "Core" to get return result. If I type "core", no result return

**Expected behavior**
I think all the filters are case insensitive, except this specific one. so I was wondering if this is a bug.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Latest

**Comment by DCMattyG** [comment]
Hi @fqzy826, I'm acknowledging this issue and am currently working on a fix to make both case-insensitive. I'll try to have this fix included in the next release, which should be coming out shortly.

Thanks for calling this out!

**Comment by DCMattyG** [comment]
Hi @fqzy826, this should now be resolved in the v3.2.0 release. Please restart your App Service to pull down the latest containers and give it a try!

**Comment by fqzy826** [comment]
Yes, it's working now. Thanks a lot !
