### ISSUE TITLE
Access denied to "Configure" page

### ISSUE THREAD

**Issue by azheaipl** [Azure/ipam#270]
**Describe the bug**
I've deployed the IPAM solution but when trying to access "Configure" page I am getting "Access denied" error. In the Web App logs I see the following entries:
2024-06-06T12:14:44.206301944Z 	Message: Access is denied to the requested resource. The user might not have enough permission.
2024-06-06T12:14:44.206307544Z 2024-06-06 12:14:44.205 | ERROR    | app.main:find_reservations:480 - Error running network check loop!
2024-06-06T12:15:05.660655405Z (AccessDenied) Please provide below info when asking for support: timestamp = 2024-06-06T12:14:44.2744940Z, correlationId = 865f0154-77d8-466d-ae90-4772e81de5f8.
2024-06-06T12:15:05.660696505Z Code: AccessDenied
2024-06-06T12:15:05.660704205Z Message: Please provide below info when asking for support: timestamp = 2024-06-06T12:14:44.2744940Z, correlationId = 865f0154-77d8-466d-ae90-4772e81de5f8.
2024-06-06T12:15:05.660709605Z Exception Details:	(AccessDenied) Access is denied to the requested resource. The user might not have enough permission.
2024-06-06T12:15:05.660714805Z 	Code: AccessDenied

Apart from that I don't see any subscriptions. But I can list all the users and grant them admin roles.
I was following this article to solve the issue https://azure.github.io/ipam/#/troubleshooting/README?id=new-azroleassignment-failed but I am the owner on the Tenant Root Group.

**Additional context**
App registrations have been created manually due to permission restrictions of service connection on the pipeline:

<img width="562" alt="image" src="https://github.com/Azure/ipam/assets/171938061/b89d4f95-9963-4d66-a0c0-6f4929f81604">
<img width="562" alt="image" src="https://github.com/Azure/ipam/assets/171938061/f9e50bc7-be15-486e-8a65-681135611635">
<img width="639" alt="image" src="https://github.com/Azure/ipam/assets/171938061/2d1340fb-d1b2-4986-bef9-cc2a3cd66ba3">

**Comment by DCMattyG** [comment]
Hi @azheaipl, thanks for reaching out!

There are many nuances to creating the required App Registrations so it's likely something was overlooked during the manual creation.

I see above that you mention that you are an Owner of the Tenant Root Group, but have you assigned the Engine Service Principal (created from the App Registration) as a **Reader** on the Tenant Root Group?

Also, the UI App Registration must be added under "**knownClientApplications**" in the Manifest of the Engine App Registration.

I'm happy to help review these configuration items with you if you'd like. Simply drop me an email to Matthew.Garrett@microsoft.com and we can setup some time to hop on a meeting during a time that is convenient for you.

**Comment by azheaipl** [comment]
Hi @DCMattyG 

Indeed, the Engine Service Principal was missing "Reader" role on the Tenant Root Group. It works, many thanks.
May I have another question if you don't mind :) What are consequences if we remove Directory.Read.All permission for UI App Registration? This is the only one permission which requires admin consent and we might not get it approved from our AD team.

**Comment by DCMattyG** [comment]
That permissions is what allows you to view the list of Users/Service Principals in the UI so you can select them and add them as Admins in the IPAM platform.

NOTE: This is a permissions all users ALREADY HAVE. This is a **delegated permission** which means the App Registration itself doesn't have the permission, this is based on the USERS permission accessing the UI. This does **not** grant any higher permission than a user already has.

It might be good to read up on Delegated vs. Application permissions so you feel more comfortable with this API permission setting:

https://learn.microsoft.com/en-us/entra/identity-platform/permissions-consent-overview#types-of-permissions

Hope that helps!

**Comment by azheaipl** [comment]
Great, thanks for support. I am closing this issue.

**Comment by DCMattyG** [comment]
Excellent, so glad you were able to get everything working!
