### ISSUE TITLE
[BUG] Deploying with AppsOnly flag throws an error

### ISSUE THREAD

**Issue by picccard** [Azure/ipam#281]
**Describe the bug**
Trying to deploy only app registrations fails.
`./deploy.ps1 -AppsOnly -UIAppName "app-reg-test-eskil" -EngineAppName "app-reg-test-eskil2"`

**Screenshots**
![image](https://github.com/Azure/ipam/assets/7443949/8f49142c-29e5-4eec-b847-710f07779126)

**Desktop (please complete the following information):**
 - OS: macOS 14.5 
 - Powershell 7.4.3
 - IPAM Release 3.1.0

**Comment by DCMattyG** [comment]
Hi @picccard, thanks for opening this issue to discuss the challenges you're running into.

I'll look into this right away, and also take a look at the PR you've submitted to address this.

Thanks for reporting this, good catch!

**Comment by picccard** [comment]
same issue seems to exist on v3.2.0

### Screenshot
![image](https://github.com/Azure/ipam/assets/7443949/431448ea-0244-4b5d-85f3-5ba46ea1f900)

**Comment by DCMattyG** [comment]
@picccard, you opened this issue after 3.2.0 was released, so you are correct that it has not been addressed yet.

Your PR's will be merged into v3.3.0 and that should address the issue shortly.
