### ISSUE TITLE
Unable to add External subnet

### ISSUE THREAD

**Issue by iamsiri007** [Azure/ipam#301]
**Describe the bug**
I have created a Space -> Block ->  External Network and when I select the External network and try to External subnet using add subnet option the app does not respond nor provide a frame to enter the details.

There are no errors in console log and also application logs.

**Expected behavior**
Option to enter the subnet details needs to be provided.

**Screenshots**
<img width="601" alt="image" src="https://github.com/user-attachments/assets/29881195-00b9-4d0d-96c7-484aff8f5923">

 - Browser: Chrome Version 126.0.6478.127 (Official Build) (arm64)

**Comment by DCMattyG** [comment]
Hey @iamsiri007, thanks so much for reporting this!

I've identified the issue and pushed the updated containers. Please restart your App Service so it will fetch the updated container and let me know if this behavior has been resolved.

Much appreciated!

**Comment by iamsiri007** [comment]
@DCMattyG Now I am able to add the external network. Issue is resolved. Thank you.

**Comment by DCMattyG** [comment]
Wonderful news @iamsiri007, thanks for confirming!
