### ISSUE TITLE
Do not see the vNet<> Block association option

### ISSUE THREAD

**Issue by rshamsz** [Azure/ipam#303]
**Describe the bug**
IPAM is installed in a test environment, where it is limited to a specific management group. The public access is disabled, and Azure PE + Private Dns Zone is used for all the Application components. I can see all the vNets and subnets that are created under the test management group, as soon as they are created.
I do not see vNET<> Block association option.

I go to  Configure > Basic > Block, when I try to associate a vNet to a Block, as it is described in the documentation, I do not see the "Virtual Networks" option after clicking on the 3 ellipses.
Although, IPAM associate the vNETs that their IP range falls under the CIDR of the created Block, automatically.

Is this the new way that vNets are associated to Blocks?

 - OS: windows 11
 - Browser [ chrome]
 - Version [127]

Thanks,

**Comment by DCMattyG** [comment]
Hi there @rshamsz, my apologies as I've been moving some items around within the UI to give certain components more room.

Here is the updated way to accomplish that:

**Menu -> Configure -> Associations**
![image](https://github.com/user-attachments/assets/edd00acb-d9cd-4960-8307-62f39dc22380)

**Select Space & Block at top**
![image](https://github.com/user-attachments/assets/68040aca-ac37-44b2-aac3-a27b3706dcd9)

I hope this helps and I'll make sure the docs are updated ASAP.

**Comment by rshamsz** [comment]
Thanks for your reply;

**Comment by rshamsz** [comment]
Thanks, it is working now.
