### ISSUE TITLE
All subnets not showing when filtering subnets by vnet

### ISSUE THREAD

**Issue by letmetechyou** [Azure/ipam#311]
**Describe the bug**
On the subnets discover page when you filter by vnet it will not show all of the subnets inside that vnet past like 128 subnets. I know this isnt working because i have a vnet with over 200 subnets and it doesnt show all of them.  speaking with microsoft they mentioned when i was running a query in the resource graph that i had to use 

resources
| where type =~ "[microsoft.network/virtualnetworks"]
| extend subnet = properties.subnets
| mv-expand subnet limit 200 | project VnetName=name

**To Reproduce**
1. Go to Discover
2. Click on Subnets
3. Filter Parent vNet
4. See only limited number of subnets if over 128 in a vnet

**Comment by DCMattyG** [comment]
Hey @letmetechyou, I'll look into this right away. Thanks for sharing all of the details as to what you did on your end to get the subnets showing up with the ARG query!

**Comment by DCMattyG** [comment]
Hi @letmetechyou, v3.4.0 has been released and should contain the fix to address your issue above.

If you're using the standard deployment, simply restart your App Service to pull down the latest containers and let me know if you can see all of the Subnets now.

If for any reason you're still not seeing the expected number of Subnets, please let me know and I'll look into it right away. Thanks much!

**Comment by DCMattyG** [comment]
Closing this issue as it has been resolved for a while now.

Please don't hesitate to open a new issue if there are any additional action items regarding this item.

Thanks so much!
