### ISSUE TITLE
Strange behaviour for reservations and associations?

### ISSUE THREAD

**Issue by MMollyy** [Azure/ipam#312]
**Describe the bug**
I have used terraform with the XtratusCloud provider to use IPAM and reserve CIDRs to deploy 3 virtual networks. A, B and C. B and C are peered to A.
I can see in the UI that the reservations exist. However, looking at the associations, I can only see 2. Namely those for A and B. The association is entirely missing for C. Additionally, both associations visible from the UI are marked as red? As if something is wrong with them.
<img width="736" alt="ipam-issue1" src="https://github.com/user-attachments/assets/9797af88-17f0-45f0-8a32-12ea8eb207bc">

Even after the virtual networks are deployed, the reservations stay in a state:
```
waiting for vNET association ...
```

**To Reproduce**
Deploy vnets using terraform XtratusCloud provider.
Check the vnets, and reservations and assocations in IPAM UI.

**Expected behavior**
I would expect that IPAM sees that the CIDRs are in use:
<img width="711" alt="ipam-issue2" src="https://github.com/user-attachments/assets/e2fc5feb-8c62-4d15-aa52-70059dde324e">
And removes the reservations from the list.

**Additional context**
I understand the [terraform provider](https://github.com/XtratusCloud/terraform-provider-azureipam/blob/main/ipamclient/reservation.go) may be the cause for the reservation, because the reservation in itself is not being deleted from terraform until a destroy is being executed. 
As it is kept in the terraform state; "It" I imagine being the unique ID for the reservation.

Even if the status of the reservation stays in waiting for association state because of terraform = I would still expect the associations to show up as working and without errors. As the identity can read the status from the RM backend.

**Comment by DCMattyG** [comment]
Hi @MMollyy, happy to help here however I can. I'm sure you know that I am **not** the owner of the XtratusCloud provider, but I have a few ideas as to what the issues could be.

Can you please provide me one of the following:
1. A sanitized/simplified version of the Terraform deployment you are attempting so I can re-create this on my end.
2. Point me to a repo where the Terraform deployment you are using is located.
3. Email me a copy of the Terraform deployment if you don't feel comfortable posting details here (Matthew.Garrett@microsoft.com)

I'm sure we can get to the bottom of this quickly, I just need a few more details so I'm not making assumptions when attempting to validate the behavior you are seeing on my end.

Much appreciated as always!

**Comment by MMollyy** [comment]
Hi @DCMattyG 
I'll be curious to your findings:

```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
    azureipam = {
      version = "~>1.0"
      source  = "xtratuscloud/azureipam"
    }
  }
}

locals {
  ipam_url = "https://XXXX.azurewebsites.net/"
  ipam_api_id = "id_pulled_from_the_application_exposed_api_section"
}

data "external" "get_access_token" {
  program = ["bash", "-c", <<EOT
    token=$(az account get-access-token --resource "api://${local.ipam_api_id}" --output json)
    access_token=$(echo $token | jq -r '.accessToken')
    echo "{\"access_token\": \"$access_token\"}"
  EOT
  ]
}

resource "azureipam_reservation" "vnet_cidr" {
  space       = var.spacename
  block       = var.blockname
  size        = 22
  description = "Reservation via terraform for vnet_cidr"
}

resource "azureipam_reservation" "vnet_cidr2" {
  space       = var.spacename
  block       = var.blockname
  size        = 22
  description = "Reservation via terraform for vnet_cidr"
}

resource "azurerm_resource_group" "rg-vnets" {
  location = "westeurope"
  name     = "rg-vnets"
}

resource "azurerm_virtual_network" "vnet-hub" {
  address_space       = [azureipam_reservation.vnet_cidr.cidr]
  location            = azurerm_resource_group.rg-vnets.location
  name                = "hub-vnet"
  resource_group_name = azurerm_resource_group.rg-vnets.name
  dns_servers         = ["#.#.#.#"]
}


resource "azurerm_virtual_network" "vnet-spoke" {
  address_space       = [azureipam_reservation.vnet_cidr2.cidr]
  location            = azurerm_resource_group.rg-vnets.location
  name                = "vnetname1"
  resource_group_name = azurerm_resource_group.rg-vnets.name
  dns_servers         = ["#.#.#.#"]
}

resource "azurerm_virtual_network_peering" "spoke1" {
  name                         = "spoke1-hub"
  remote_virtual_network_id    = azurerm_virtual_network.vnet-hub.id
  resource_group_name          = azurerm_resource_group.rg-vnets.name
  virtual_network_name         = azurerm_virtual_network.vnet-spoke.name
  allow_forwarded_traffic      = true
  allow_virtual_network_access = true
}

resource "azurerm_virtual_network_peering" "hub`" {
  name                         = "hub-spoke1"
  remote_virtual_network_id    = azurerm_virtual_network.vnet-spoke.id
  resource_group_name          = azurerm_resource_group.rg-vnets.name
  virtual_network_name         = azurerm_virtual_network.vnet-hub.name
  allow_forwarded_traffic      = true
  allow_virtual_network_access = true
}

```

I believe that should be all of it for just the vnets. Uh, if you dont have bash on your local system but powershell instead, this will also work for the access token:
``` 
data "external" "get_access_token" {
  program = ["powershell", "-Command", <<EOT
    $token = az account get-access-token --resource "api://${local.ipam_api_id}" | ConvertFrom-Json
    $result = @{access_token = $token.accessToken} | ConvertTo-Json -Compress
    Write-Output $result
  EOT
  ]
}
```

**Comment by DCMattyG** [comment]
Hi @MMollyy, looking at this I can already tell you what's wrong.

It's important to understand that when you create a **Reservation**, once piece of information you get back is a TAG which needs to be applied to the newly created Virtual Network in order for the Azure IPAM platform to be able to map the Virtual Network in Azure back to the **Reservation** in Azure IPAM.

Here you can see this is noted in one of the XtratusCloud examples:

![image](https://github.com/user-attachments/assets/23c8409e-917d-47a1-bc0c-9694a3873941)

So, I believe that is all you are missing. Please give that a try and see if you have better luck getting everything working as expected.

**Comment by MMollyy** [comment]
I totally missed that part for some reason! That does indeed fix the reservations from staying in a waiting for association state.
My apologies, and thanks for the help.

**Comment by DCMattyG** [comment]
Wonderful news, glad that it was something simple!
