### ISSUE TITLE
Unable to add External Network after removing Reservation

### ISSUE THREAD

**Issue by ckasperscadac** [Azure/ipam#328]
**Describe the bug**

**To Reproduce**
1. Reserve a network
2. Remove the Reservation
3. Try to add this network as External
4. Get an error that the network is reserved

**Expected behavior**
I expect to be able to add the External network after removing the Reservation.

**Screenshots**
![image](https://github.com/user-attachments/assets/edb1f7f8-235b-4538-b6ad-3120fb520640)
![image](https://github.com/user-attachments/assets/3fc8425b-5108-4f8c-97c3-568436b3143e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version 129.0.2792.65

**Comment by DCMattyG** [comment]
Hi @ckasperscadac, thanks for reporting this issue!

I'll reproduce this on my end and report back my findings shortly with next steps.

**Comment by ckasperscadac** [comment]
Hi @DCMattyG, any update on this?

**Comment by DCMattyG** [comment]
Hi @ckasperscadac, I have located the issue and will get an updated release out shortly. Will keep you posted on the release process here.

**Comment by ckasperscadac** [comment]
Hi @DCMattyG how is the update coming along?

**Comment by ckasperscadac** [comment]
Hello @DCMattyG do you have any news on the release?

**Comment by DCMattyG** [comment]
Hi @ckasperscadac, apologies for the very long delay on addressing this issue.

Code is done and staged in a new branch. New version (v3.5.0) will be released over the weekend containing this fix as well as several others.

**Comment by DCMattyG** [comment]
Azure IPAM v3.5.0 has now been released and contains the fix for this issue.

Release Notes: https://github.com/Azure/ipam/releases/tag/v3.5.0

Please give it a test and let me know if you have any remaining issues with this. Thanks!

**Comment by ckasperscadac** [comment]
Hi @DCMattyG the issue appears to have been resolved, thanks!
