### ISSUE TITLE
IPAM UI isn't loading

### ISSUE THREAD

**Issue by aazherelyeu** [Azure/ipam#330]
Hi,

I built IPAM with -PrivateACR flag without any changes in the code. The UI isn't loading:

![Image](https://github.com/user-attachments/assets/d675132e-ce2e-46d9-baca-0feee773f3ca)

In the Web APP logs I see the following:

2024-10-15T22:58:55.8917016Z Message: Please provide below info when asking for support: timestamp = 2024-10-15T22:58:55.7969739Z, correlationId = a02a03ff-d2ee-41a8-9592-d53384b9f494.
2024-10-15T22:58:55.8917128Z Exception Details:	(AccessDenied) Access is denied to the requested resource. The user might not have enough permission.
2024-10-15T22:58:55.8917261Z 	Code: AccessDenied
2024-10-15T22:58:55.8917349Z 	Message: Access is denied to the requested resource. The user might not have enough permission.
2024-10-15T22:58:55.8917471Z 2024-10-15 22:58:55.890 | INFO     | uvicorn.protocols.http.httptools_impl:send:468 - *******:12665 - "GET /api/status HTTP/1.1" 200
2024-10-15T22:59:29.4404903Z 2024-10-15 22:59:29.438 | ERROR    | app.dependencies:validate_token:209 - Microsoft Identity v1.0 access tokens are not supported!
2024-10-15T22:59:29.4407197Z 2024-10-15 22:59:29.438 | ERROR    | app.dependencies:validate_token:210 - https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens#token-formats

**Comment by DCMattyG** [comment]
Hi @aazherelyeu, appreciate you reaching out here and of course happy to help!

Are you able to provide any logs from the deployment?

First and foremost, it looks like you may have manually created the Service Principals. I can see from the error message above that the SP is configured to use a v1 token, and the scripts provided in the repo for deployment specifically build them with v2 enabled.

Additionally it looks like some SP permissions might be missing?

Can you provide me more details around exactly how this was deployed (e.g. commands that were used) and perhaps how the Service Principals were created?

Thanks so much!

**Comment by aazherelyeu** [comment]
Hello,

The log is attached. 

App registrations were created manually. IPAM was installed with the following command:
.\deploy.ps1 -Location "${{ parameters.Location }}" -ResourceNames $ResourceNames -ParameterFile ./main.parameters.json -PrivateACR

In main.parameters.json I passed AppID of UI and engine as well as secret.

The screenshots are below:

**UI:**
![Image](https://github.com/user-attachments/assets/75a5c015-c09c-4eba-86fc-147327459091)

**Engine:**
![Image](https://github.com/user-attachments/assets/0a863922-ed0e-449f-a381-c8f177a6c624)

![Image](https://github.com/user-attachments/assets/2c3c0e04-dfb0-4e0d-a0fe-5c1fb156a4fb)



[deploy_20241016093853AM.log](https://github.com/user-attachments/files/17398667/deploy_20241016093853AM.log)

**Comment by DCMattyG** [comment]
Thanks for clarifying @aazherelyeu.

You will also need to make sure the "acceptedTokenVersion" is set to "2" and the Engine App Registration is aware of the UI App Registration by way of "knownClientApplications", both of which are in the manifest for the App Registrations.

Furthermore, you will need to make sure the Engine has been granted Admin Consent and this is a backend app and users cannot be presented with a consent window.

All of the above are taken care of by the provided scripting, so if you have more issues you may want to consider deploying the App Registrations & Service Principals via script instead of manually.

**Comment by aazherelyeu** [comment]
UI is working now once I set the following parameters in the manifest:

"acceptedTokenVersion" is set to "2".
"knownClientApplications" is set to AppID of UI app registration.

Additionally, I'd like to get an access token as described here:
https://azure.github.io/ipam/#/api/README

But I get the following error:

**$accessToken = ConvertTo-SecureString (Get-AzAccessToken -ResourceUrl api://0ef88435-f5ad-42d6-9630-ed3eb2ed835d).Token -AsPlainText**
WARNING: Upcoming breaking changes in the cmdlet 'Get-AzAccessToken' :
The Token property of the output type will be changed from String to SecureString. Add the [-AsSecureString] switch to avoid the impact of this upcoming breaking change.
- The change is expected to take effect in Az version : '13.0.0'
- The change is expected to take effect in Az.Accounts version : '4.0.0'
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.
Get-AzAccessToken: ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)

Content:
{"error":{"code":"AudienceNotSupported","message":"Audience api://0ef88435-f5ad-42d6-9630-ed3eb2ed835d is not a supported MSI token audience."}}

Headers:
X-Powered-By: REDACTED
ETag: W/"90-cpTBODqslv24YIwwUr0BCk547sw"
Date: Wed, 16 Oct 2024 19:06:42 GMT
Connection: keep-alive
Keep-Alive: REDACTED
Content-Type: application/json; charset=utf-8
Content-Length: 144

See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
ConvertTo-SecureString: Cannot bind argument to parameter 'String' because it is null.

**Comment by DCMattyG** [comment]
For the `Get-AzAccessToken` command, it looks like you are using the incorrect `-ResourceURL`. From your own screenshot above, the API URL should look like this:

![Image](https://github.com/user-attachments/assets/365514ac-7b5a-4266-9096-d0d3a21bae28)

Did I read that correctly?

**Comment by aazherelyeu** [comment]
I recreated App registration. So, it has a new ID

![Image](https://github.com/user-attachments/assets/1c9ce77c-fc04-44af-b1cc-8fd2a292ba77)

**Comment by DCMattyG** [comment]
Hey @aazherelyeu, I did some testing myself and after creating a net-new App Registration, it took some time before the `Get-AzAccesstoken` would work. After about 1HR, everything is working as expected.

Can you check if you're seeing the same behavior on your end?

**Comment by aazherelyeu** [comment]
Hi Matthew,

Still the same issue :(

I was testing UI functionalities, all seem to be working fine. When I tried in Swagger I got this error for all API calls:
![Image](https://github.com/user-attachments/assets/706d54de-cd22-42bc-af6d-8aa34ba93099)


In Postman all is good:
![Image](https://github.com/user-attachments/assets/be6efa79-50a7-4488-9367-abb070ae7c76)

**Comment by DCMattyG** [comment]
Got it @aazherelyeu.

And when you re-created the App Registration, you were sure to add in the Authorized Client Applications (from your screenshots above)?

![Image](https://github.com/user-attachments/assets/d15fcdae-fedd-4086-98c0-908aa07b8fd8)

These are what allow a token to be generated from the Azure CLI and Azure PowerShell.

**Comment by aazherelyeu** [comment]
Yes, they are added as well:

![Image](https://github.com/user-attachments/assets/896472a9-ca60-4597-a740-c1c15268b250)

**Comment by DCMattyG** [comment]
Thanks for confirming @aazherelyeu.

At this point I'm not sure why you are unable to generate a token using PowerShell. I've created one manually on my end and everything appears to be working from what I can see. I'm more than happy to schedule a Teams meeting with you to review everything and see what might be missing. If that sounds like something you'd be interested in please drop me an email at Matthew.Garrett@microsoft.com and we'll put some time on the calendar.

Out of curiosity, can you try generating the App Registrations using the scripting I've provided & thoroughly tested?

You can generate only the App Registrations by using the [App Identities Only](https://azure.github.io/ipam/#/deployment/README?id=azure-identities-only-deployment) deployment as shown in the docs.

**Comment by aazherelyeu** [comment]
I will test the script in my private subscription. The weird thing is that everything is working in UI as well as in Postman but not working in Swagger.

I will sent you an email regarding testing of generating tokens using Powershell.
