### ISSUE TITLE
"Cannot bind parameter 'AccessToken'. Cannot convert the value of type "System.String" to type "System.Security.SecureString"."

### ISSUE THREAD

**Issue by onsenturk** [Azure/ipam#332]
When I try to run deploy.ps1 from the Azure Shell to install IPAM, I get the following error message

PS /home/mod/ipam/deploy> cat /home/mod/ipam/logs/error_20241105105500AM.log
Grant-AdminConsent: /home/mod/ipam/deploy/deploy.ps1:1144
Line |
1144 |        Grant-AdminConsent @consentDetails -AzureCloud $azureCloud -Dis …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind parameter 'AccessToken'. Cannot convert the value of type "System.String" to type "System.Security.SecureString".

PS /home/mod/ipam/deploy> cat /home/mod/ipam/logs/deploy_20241105105500AM.log
**********************
PowerShell transcript start
Start time: 20241105105500
Username: SandboxHost-638664003710251273\mod
RunAs User: SandboxHost-638664003710251273\mod
Configuration Name: 
Machine: SandboxHost-638664003710251273 (Unix 5.10.102.2)
Host Application: /opt/microsoft/powershell/7/pwsh.dll -NoLogo
Process ID: 356
PSVersion: 7.4.5
PSEdition: Core
GitCommitId: 7.4.5
OS: CBL-Mariner/Linux
Platform: Unix
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0, 7.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************

NOTE: IPAM Deployment Type: AppContainer
INFO: Fetching Tenant ID from Azure PowerShell SDK
INFO: Fetching Azure Cloud type from Azure PowerShell SDK
INFO: Validating Azure Region selected for deployment
INFO: Azure Region validated successfully
INFO: Creating Azure IPAM UI Application
INFO: Creating Azure IPAM Engine Application
INFO: Updating Azure IPAM Engine API Endpoint
INFO: Updating Azure IPAM UI Application Resource Access
INFO: Creating Azure IPAM UI Service Principal
INFO: Creating Azure IPAM Engine Service Principal
INFO: Creating Azure IPAM Engine Secret
INFO: Azure IPAM Engine & UI Applications/Service Principals created successfully
WARNING: Upcoming breaking changes in the cmdlet 'Get-AzAccessToken' :
The Token property of the output type will be changed from String to SecureString. Add the [-AsSecureString] switch to avoid the impact of this upcoming breaking change.
- The change is expected to take effect in Az version : '13.0.0'
- The change is expected to take effect in Az.Accounts version : '4.0.0'
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.
INFO: Logging in to Microsoft Graph
PS>TerminatingError(Connect-MgGraph): "Cannot bind parameter 'AccessToken'. Cannot convert the value of type "System.String" to type "System.Security.SecureString"."
>> TerminatingError(Grant-AdminConsent): "Cannot bind parameter 'AccessToken'. Cannot convert the value of type "System.String" to type "System.Security.SecureString"."
ERROR: Unable to deploy Azure IPAM solution due to an exception, see logs for detailed information!
Run Log: /home/mod/ipam/logs/deploy_20241105105500AM.log
Error Log: /home/mod/ipam/logs/error_20241105105500AM.log

**********************
PowerShell transcript end
End time: 20241105105516
**********************

**Comment by DCMattyG** [comment]
Hi @onsenturk, apologies for the delay in response but I've located the issue here.

The reason you're facing this revolves around how the script determines what version of `Microsoft.Graph` is available and the different way that Cloud Shell loads modules (on demand). It never really loads the main `Microsoft.Graph` as it's not part of the requirements at the top of the deployment script, so I had to change the way I validate the Graph version.

This will fix will be incorporated into the next version which should be available shortly.

Thanks so much for the feedback and help us make the product even better!

**Comment by onsenturk** [comment]
Thanks a lot..
I also fixed the issue my changing the code 👍👍
But thanks for the feedback.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DCMattyG** [comment]
This has now been address in Azure IPAM v3.5.0

Release Notes: https://github.com/Azure/ipam/releases/tag/v3.5.0

Please let me know if you run into any further issues regarding this topic, and thank you for bringing this to my attention so it could be quickly addressed!
