### ISSUE TITLE
 Unable to deploy Azure IPAM solution due to an exception

### ISSUE THREAD

**Issue by letmetechyou** [Azure/ipam#39]
**Describe the bug**
get the error unable to deploy azure ipam due to an exception 

**To Reproduce**
ran the .\deploy.ps1 -Location "eastus" 

and got the following error 

Line |
 737 |      $azureCloud = $AZURE_ENV_MAP[(Get-AzContext).Environment.Name]
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Index operation failed; the array index evaluated to null.

do i need to set this beforehand

**Comment by DCMattyG** [comment]
Hi @letmetechyou, before you run the deploy script have you connected to Azure using the ```Connect-AzAccount``` command and set your target subscription using ```Set-AzContext```?

**Comment by letmetechyou** [comment]
This fixed the issue.  Thanks.

**Comment by DCMattyG** [comment]
Hi @hannovdm, the value for this is pulled dynamically from the Azure PowerShell Context when the deployment script runs. You must connect to Azure PowerShell and set the context within the same window (session) which you execute the deployment script.

Take a look at the walk-through here in ours docs: https://azure.github.io/ipam/#/deployment/README?id=deployment-overview

Give that a try and let me know if you are still having any issues. If so, don't hesitate to reach out to me via email at Matthew.Garrett@microsoft.com and I'm happy to give you some 1:1 assistance with this.
