### ISSUE TITLE
Deployment with -PrivateACR

### ISSUE THREAD

**Issue by Garyforsman** [Azure/ipam#42]
If I deploy the solution with -PrivateACR enabled, the deployment is successful, however the service does not actually work. Seems to be something with the docker instances being in a read-only mode

UI Error post deployment attached

![image](https://user-images.githubusercontent.com/50968447/198192827-5bde4814-4e9f-4191-98f3-d76be0077a48.png)

Log trace from App service logger
/home/LogFiles/2022_10_19_ln0sdlwk0006EW_docker.log  (https://acrip-7nk45gqrphpc6.scm.azurewebsites.net/api/vfs/LogFiles/2022_10_19_ln0sdlwk0006EW_docker.log)
2022-10-19T04:59:09.967132977Z /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
2022-10-19T04:59:09.970722633Z /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
2022-10-19T04:59:09.975609708Z 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
2022-10-19T04:59:09.975902013Z /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
2022-10-19T04:59:09.984075840Z /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
2022-10-19T04:59:09.993215582Z /docker-entrypoint.sh: Configuration complete; ready for start up
2022-10-19T04:59:10.110001396Z 2022/10/19 04:59:10 [emerg] 1#1: host not found in upstream "ipam-ui" in /etc/nginx/conf.d/default.conf:5
2022-10-19T04:59:10.110044397Z nginx: [emerg] host not found in upstream "ipam-ui" in /etc/nginx/conf.d/default.conf:5

**Comment by DCMattyG** [comment]
Hi @Garyforsman, thanks so much for reaching out!

Couple of questions...

1) Have you made sure that you've followed all of the prerequisites as shown in the docs here?

https://azure.github.io/ipam/#/deployment/README?id=prerequisites

2) I'm assuming you were doing a Full deployment, did you add any other flags besides "-PrivateACR"?

3) During the deployment, did you see any warnings/error messages?

From the above, it appears that NGINX cannot find the ipam-ui container running, which seems to me like something potentially failed in the docker build/push phase of the deployment script.

Please check the above, and if you're still having issues, I'm always happy to schedule a 1:1 session to help you out!

**Comment by Garyforsman** [comment]
Hey @DCMattyG, thank you for the reply...much appreciated. 
1. I have followed the prerequisites as documented in that link, I should also add that I am able to get a working deployment if I do and full deployment and do not use -PrivateACR
2. Correct, I am doing a full deployment with -PrivateACR
3. There are no errors noted during deployment

I will deploy again with the -PrivateACR flag on now and see if there are any errors noted. Will ping back here

**Comment by Garyforsman** [comment]
WARNING: Selected Microsoft Graph profile 'v1.0' does not exist for module 'Microsoft.Graph.Financials'. No cmdlets were loaded.
WARNING: Selected Microsoft Graph profile 'v1.0' does not exist for module 'Microsoft.Graph.ManagedTenants'. No cmdlets were loaded.
WARNING: Selected Microsoft Graph profile 'v1.0' does not exist for module 'Microsoft.Graph.WindowsUpdates'. No cmdlets were loaded.

NOTE: IPAM Deployment Type: Full
INFO: PrivateACR flag set, verifying minimum Azure CLI version
INFO: PrivateACR flag set, verifying Azure PowerShell and Azure CLI contexts match
INFO: Fetching Tenant ID from Azure PowerShell SDK
INFO: Fetching Azure Cloud type from Azure PowerShell SDK
INFO: Validating Azure Region selected for deployment
INFO: Azure Region validated successfully
INFO: Creating Azure IPAM UI Application
INFO: Creating Azure IPAM Engine Application
INFO: Updating Azure IPAM Engine API Endpoint
INFO: Updating Azure IPAM UI Application Resource Access
INFO: Creating Azure IPAM UI Service Principal
INFO: Creating Azure IPAM Engine Service Principal
INFO: Creating Azure IPAM Engine Secret
INFO: Azure IPAM Engine & UI Applications/Service Principals created successfully
INFO: Logging in to Microsoft Graph
INFO: Granting admin consent for Microsoft Graph API permissions assigned to IPAM UI application
INFO: Admin consent for Microsoft Graph API permissions granted successfully
INFO: Granting admin consent to the IPAM UI application for exposed API from the IPAM Engine application
INFO: Admin consent for IPAM Engine exposed API granted successfully
INFO: Granting admin consent for Azure Service Management API permissions assigned to IPAM Engine application
INFO: Admin consent for Azure Service Management API permissions granted successfully
INFO: Deploying IPAM bicep templates
INFO: IPAM bicep templates deployed successfully
INFO: Updating UI Application with SPA configuration
INFO: UI Application SPA configuration update complete
INFO: Building and pushing container images to Azure Container Registry
INFO: Building Engine container (Debian)...
INFO: Engine container image build and push completed successfully
INFO: Building UI container (Debian)...
INFO: UI container image build and push completed successfully
INFO: Restarting App Service
INFO: Azure IPAM Solution deployed successfully

**Comment by DCMattyG** [comment]
Thanks for the output from the deploy script!

It looks like you might want to verify the version of the Graph module you have installed as you shouldn't be seeing those warnings...

![image](https://user-images.githubusercontent.com/12955732/198207668-649ca162-2bed-4e14-bcc6-bf8a79ec976f.png)

If you could, check the App Service logs to see if it's having any trouble pulling the containers from your Private ACR, or starting the multi-container app.

Worst case, reach out to me at Matthew.Garrett@microsoft.com and I'll setup some time to look over everything with you. It's possible we've missed some error check in the current deploy script that you've run into.

**Comment by satsuk81** [comment]
@DCMattyG, I too am getting the same issue when using -PrivateACR

I've recently been looking at IPAM solutions and this one seems the best fit but I am looking to extend your argquery.py file to include filtering based on Azure Tags.

When using -PrivateACR, everything deploys but the UI doesnt work, and investigations also point to the init.sh files being missing.

Have tried Full and TemplateOnly deployments but neither work.

I also get the Microsoft.Graph warnings so have tried 1.15.x and 1.9.6.
I have also tried executing the ps1 script from within VSCode and from PowerShell terminal.

Any advice welcome as I'm actively trying to get this working.

Thanks,
Dan.

**Comment by DCMattyG** [comment]
Hi @satsuk81, I have a branch with the fixes for this which will be merged today. For now, you can use the "nginx-ubi8" branch to deploy and the -PrivateACR flag should indeed work.

Please test and let me know if you run into any issues. Thanks so much!

**Comment by DCMattyG** [comment]
Fixes have been pushed, please let me know if you have any further issues on this topic!

**Comment by satsuk81** [comment]
@DCMattyG, unfortunately issue still remains.  I tested yesterday with your branch and today on main.

![image](https://user-images.githubusercontent.com/76114734/200530898-49be2a30-1694-4093-8fda-69e051ba8987.png)

![image](https://user-images.githubusercontent.com/76114734/200530965-9802939d-ba07-4aea-be71-11ba6aba9f02.png)

[log.zip](https://github.com/Azure/ipam/files/9959777/log.zip)

**Comment by DCMattyG** [comment]
Hi @satsuk81, it appears you may still be using older code as the error present in the logs was something that I patched in the latest update. Can you please try deleting the cloned folder on your local machine, re-cloning from GitHub, and trying once more?

If that still doesn't work, drop me an email at Matthew.Garrett@microsoft.com for some more 1:1 troubleshooting we can try.

Thanks!

**Comment by satsuk81** [comment]
@DCMattyG thank you.

I have run a few tests and can confirm that I have a working solution with the -PrivateACR switch set.

I do not know what my cloned space had in it that prevented it from working as I could see all your latest code changes.
