### ISSUE TITLE
Unable to View VNETS or SUBNETS after associating in Block

### ISSUE THREAD

**Issue by bpfoley45** [Azure/ipam#57]
**Describe the bug**
After following the How-to guide and creating Spaces, associated a Block with it then assigning a vnet to it as outlined here:
https://azure.github.io/ipam/#/how-to/README?id=virtual-network-association
I am then able to see the Spaces and Blocks under the discover tab, but no vnets or subnets. Curiously, it also shows that the Block is 100% allocated, which it is not. I have tried on a few subscriptions, some with existing vnets and others I just created and the behavior is identical. 

Deployment was done via App Services model and there were no recorded errors in the deployment (ran with -Verbose switch). Porcess was performed with a Global Admin account. The ipam-engine-app principal is applied successfully at the root management group and propagates to other MGs in the hierarchy. 

**Expected behavior**
See vnets and subnets listed under the discover tab

**Additional context**

**Comment by DCMattyG** [comment]
Hello @bpfoley45, thank you so much for reaching out!

You mentioned that "deployment was done via App Services model", but does that mean you used the included Deployment script and followed the "Full" deployment steps in our guide? If so, can you share the deployment logs from the "log" folder?

When you load the IPAM Web UI, do you see an HTTP 200 status for the API calls which load the vNET/Subnet/Endpoint details (as pictured below)?

![image](https://user-images.githubusercontent.com/12955732/205118820-2d6ae23e-c34f-4a2c-b39b-5f28f8072347.png)

Additionally, I'm happy to assist you 1:1, just reach out to me at Matthew.Garrett@microsoft.com and I can arrange some time to go over the install with you and help to identify any issues.

Thanks so much, we'll get you up & running ASAP!

**Comment by bpfoley45** [comment]
vnet reports an HTTP 500

attached are the logs:
[zip.zip](https://github.com/Azure/ipam/files/10134943/zip.zip)

**Comment by DCMattyG** [comment]
Can you help me understand how this was deployed? This doesn't appear to have been deployed from the script we provide in the /deploy folder (though I may be mistaken).

**Comment by bpfoley45** [comment]
sorry, I neglected to include that- I deployed it via 

`.\deploy.ps1 -Location eastus -Verbose`

**Comment by DCMattyG** [comment]
Have you assigned yourself as an "Admin" in IPAM yet, or is the admins section still empty (e.g. everyone is an Admin)?

**Comment by bpfoley45** [comment]
I did, I assigned it to myself (same user that deployed the solution)

**Comment by bpfoley45** [comment]
Yes, I do have some IPv6 space in a single vnet...but it is not part of the space/block that I have added

**Comment by DCMattyG** [comment]
Can you try something for me....

In the Subscription exclusions section (Admin -> Subscriptions), can you exclude the subscription which contains the IPv6 vNET (highlight in red), then click "save" (in the upper right). After that, test again to see if you can see the vNETs/Subnets.

Docs page: https://azure.github.io/ipam/#/how-to/README?id=subscription-exclusioninclusion

The errors are showing that an invalid address is trying to be parsed as IPv4 and that is causing a crash. I'll definitely address this, but I'd like to confirm my suspicion first.

Really appreciate the help!

**Comment by bpfoley45** [comment]
Success!

**Comment by DCMattyG** [comment]
Ok, definitely an IPv6 issue. I'll get to work on this right away!

If you could share with me some details on the IPv6 vNET/Subnet you have which I can use as a reference, that would be awesome.

You can email me directly if you don't want to share the details here: Matthew.Garrett@microsoft.com

**Comment by bpfoley45** [comment]
I was using unique local, specifically fd00:db8:deca::/48

**Comment by bpfoley45** [comment]
correct, it was defined at the address space and then at the subnet level below it

**Comment by DCMattyG** [comment]
You're awesome @bpfoley45, I'll work on a code fix for this and keep you posted so you can re-test after I get the new code pushed out!

**Comment by DCMattyG** [comment]
Hey @bpfoley45, I just wanted to let you know that the fix for this has been pushed into the *main* branch, and the production containers have been updated. If you're running the **Full** deployment (from the Deployment script), simply restart your App Service (assuming it's not currently pointed at the DEV containers) and you should be good to go.

Please let me know if you have any other issues, otherwise if things are working well let me know if I'm good to close this issue for now. Really appreciate you helping us get to the bottom of this one!

**Comment by DCMattyG** [comment]
Good morning @bpfoley45, just wanted to check in with you one more time on this. Your issue should now be resolved and I wanted to make sure that you are satisfied with the results. Please let me know if you have any issue with the fix in the current codebase. Thanks!

**Comment by DCMattyG** [comment]
Hello @bpfoley45, as this fix has been incorporated for a while now, and I haven't heard back from you, I'm hoping all is working well and you're enjoying the Azure IPAM tool. I'm going to close this issue for now, but if at any point you're still seeing this issue (or any other for that matter), please do not hesitate to open another issue, or reach out directly to us. We're always here to help!
