### ISSUE TITLE
Feature request: Adding virtualWAN subnet to subnet discovery

### ISSUE THREAD

**Issue by pcdiks** [Azure/ipam#60]
I would like to see the subnet that is used by the virtualWAN to be discovered so that I can associated that with a block that I added.
![image](https://user-images.githubusercontent.com/16719277/205642200-a5d70f31-243a-440b-90af-beb0a14c8cac.png)

**Comment by DCMattyG** [comment]
Hi @pcdiks, I spent quite a bit of time today looking into this, and here are my thoughts...

A traditional Virtual Network in Azure has a relationship like this:

Virtual Network -> Subnet(s) -> Endpoint(s)

When you create a vWAN Hub, you assign Address Space to it, just like a normal Virtual Network. However, it's essentially a "black box". You can put "stuff" in that Address Space, you can "peer" (connect) it to other Virtual Networks, but you can't create Subnets, or do anything directly with the Address Space of that vWAN Hub. In fact, when you "peer" it, that peering is to a mystery subscription that you don't control and have no visibility into.

That said, I completely understand that the Address Space you assign to the vWAN Hub does indeed subtract from your overall Enterprise IP space, and you'd like to account for it within IPAM.

So.....in an ideal world, how best should this look?

Should we just "fake" it and say that a vWAN Hub is essentially a vNET for the purposes of IPAM? Or should there be a special section to handle the strange nuances of vWAN within IPAM?

I'm very interested in how you think this is best represented in the tool.

**Comment by pcdiks** [comment]
Hi @DCMattyG , for me the most important part would be that I can remove it from the available addresses so that that subnet is not available for a reservation. Creating a special kind of vnet for the vwan would be nice since you cannot do anything with it.
From my point of view it is not necessary to add any special features to IPAM to handle that vnet.

**Comment by DCMattyG** [comment]
Hi there @pcdiks, I know it took a while, but support for vWAN Hubs has now been merged in from PR #113.

Please restart your Azure IPAM App Service, and the latest containers should be pulled down. Let us know if you have any issues with the new feature. Enjoy!

**Comment by pcdiks** [comment]
Hi, I just updated a couple of my deployments and they work great. Thanks!
