### ISSUE TITLE
Database creation fails

### ISSUE THREAD

**Issue by TheMorganator** [Azure/ipam#61]
**Describe the bug**
On first startup of engine container the database is not created.

Error in logstream:
/home/LogFiles/2022_12_15_ln1sdlwk000F0E_ipam-engine_docker.log  (https://<redacted>.scm.azurewebsites.net/api/vfs/LogFiles/2022_12_15_ln1sdlwk000F0E_ipam-engine_docker.log)
2022-12-15T23:11:57.446430985Z Message: "Operation 'POST' on resource 'dbs' is not allowed through Azure Cosmos DB endpoint. Please switch on such operations for your account, or perform this operation through Azure Resource Manager, Azure Portal, Azure CLI or Azure Powershell"

**To Reproduce**
1. Deploy with deploy.ps1 script
2. Access UI
3. Nothing happens; no data, UI stuck

**Expected behavior**
Database should be created

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 110

**Comment by DCMattyG** [comment]
Hey @TheMorganator, as per my note in your other issue #62, please check the prerequisites section, send over the deployment logs, and reach out to me directly at Matthew.Garrett@microsoft.com at any time. We're here to help!

**Comment by DCMattyG** [comment]
Hey @TheMorganator, per the other issue you have open, we spent some time on this outside of this thread and I believe you're up & running now. Any fixes that we got into DEV are now pushed to the *main* branch, and also available from the updated production containers.

Please let me know if you're happy with everything, and if we're good to close this issue. Thanks so much!

**Comment by DCMattyG** [comment]
Good morning @TheMorganator, just wanted to circle back with you on this. As mentioned above, the fix for this is now incorporated into the main codebase. If you have any issues, please let me know so we can get you fixed up right away, otherwise confirm if I'm ok to close this issue if everything is resolved. Thank you so much for your partnership!

**Comment by DCMattyG** [comment]
Hello @TheMorganator , as this fix has been incorporated for a while now, and I haven't heard back from you, I'm hoping all is working well and you're enjoying the Azure IPAM tool. I'm going to close this issue for now, but if at any point you're still seeing this issue (or any other for that matter), please do not hesitate to open another issue, or reach out directly to us. We're always here to help!
