### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by CiscoNCS** [Azure/ipam#73]
Hi trying to deploy this solution in azure nearly all worked fine apart from some identity stuff which i presume is causing subscriptions to not appear error is below 

New-AzRoleAssignment: /usr/local/share/powershell/Modules/Az.Resources/6.5.1/MSGraph.Autorest/custom/New-AzADServicePrincipal.ps1:752
Line |
 752 |        $ra = New-AzRoleAssignment @param
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation returned an invalid status code 'Forbidden'

**Comment by CiscoNCS** [comment]
Human error...

**Comment by DCMattyG** [comment]
Hey @CiscoNCS, so glad you got everything working. If you ever need anything, don't hesitate to reach out. Enjoy Azure IPAM!
