### ISSUE TITLE
Subscription page is returned blank

### ISSUE THREAD

**Issue by AndersAsp** [Azure/ipam#74]
**Describe the bug**
The Subscription section under Admin is returning blank. You can briefly see the basics of the page only for it to then disappear and go blank.

**To Reproduce**
1. Open Azure IPAM
2. Expand the menu
3. Expand Admin
4. Click Subscriptions

**Expected behavior**
I expect all the Subscriptions to be loaded and manageable.
Everything else in the IPAM Solution seems to work fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/15642016/215789540-921c23a0-cc35-4d9b-86b3-472879054647.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 (22621.1105)
 - Browser: Edge (Version 109.0.1518.70 (Official build) (64-bit))

**Comment by DCMattyG** [comment]
Hey there @AndersAsp, thank you for bringing this to my attention!

When you load the subscriptions page, can you watch under Networking in the Web Developer Tools (as opposed to console above) and check the Response from the "subscriptions" API call? Are any of them missing an "id" field?

![image](https://user-images.githubusercontent.com/12955732/215804089-f9934e7c-2a6c-48cf-88bf-443e9c8fa009.png)

Prior to this, have you set any exclusions?

Thanks for the feedback, we'll get this fixed up ASAP!

**Comment by AndersAsp** [comment]
Hi @DCMattyG!

I do get a returned list of 106 Subscriptions, but all of them seems to have Id as expected. 
The only strange things I see in the returned data is:
![image](https://user-images.githubusercontent.com/15642016/215972363-2bf565c1-0ccf-4710-85c3-89e95c2ee90a.png)

and a handful of Subscriptions of where the Type is Unknown.

It has previously been working and we've done some exclusions. I do see the response from "exclusions" is returning 40 subscription ids.

**Comment by DCMattyG** [comment]
Thanks for checking that @AndersAsp!

I'm about to release the latest code, can you point your App Service at the DEV containers by following the instructions on [THIS](https://github.com/Azure/ipam/discussions/50#discussioncomment-4710593) discussion and see if your issue is resolved in the latest codebase?

**Comment by AndersAsp** [comment]
Yup! Using the DEV containers it seems to be working fine!

**Comment by DCMattyG** [comment]
Hey there @AndersAsp, just letting you know the fix has been pushed to the *main* branch now, and the production containers should be working for you. Let me know if you have any issues, and thanks again for the teamwork here!
