### ISSUE TITLE
Error accessing the analysis-visualize screen

### ISSUE THREAD

**Issue by XtratusCloud** [Azure/ipam#83]
**Describe the bug**
When accessing the analysis-visualize option, before selecting a space, the following error occurs in the console and the page is not displayed.

**To Reproduce**
1. Go to 'Analysis'
2. Click on 'Visualize'
3. See error in console

**Expected behavior**
The page expected to be rendered and displayed, allowing to select a space.

**Screenshots**
![image](https://user-images.githubusercontent.com/122672536/220334949-e4a6b83e-c2c5-4462-8499-874637250a9a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 110.0.1587.50

**Additional context**
The error occurs iterating the existing endpoints in each subnet, in the file /ui/src/features/analysis/visualize.js.
Is related to the information of the existing subnets in our subscriptions.
I temporarily prevent it by checking that the variable endpoint is not null, or by removing the call to the .toLowerCase() method.

**Comment by DCMattyG** [comment]
Hello @XtratusCloud, I can see from the code snippet that this doesn't appear to be running the most recent code from the **main** branch of the repo. Can you help me confirm if this issue is still present in the latest codebase?

**Comment by XtratusCloud** [comment]
I have verified that the error no longer occurs after taking the latest version in the main branch.

The bug can be closed.
Thanks!!!
