### ISSUE TITLE
Subscription Name in visualize and peering tooltips

### ISSUE THREAD

**Issue by XtratusCloud** [Azure/ipam#87]
**Is your feature request related to a problem? Please describe.**
A large number of managed subscriptions and the id is not significant to identify the subscription.

**Describe the solution you'd like**
It would be very useful if the tooltips displayed in the "visualize" and "peering" options would include the subscription name.

**Describe alternatives you've considered**

**Additional context**

**Comment by DCMattyG** [comment]
This is a great call out @XtratusCloud. I'll get working on this right away. I've had similar requests from other users so it's time to get the subscription name added to all of the components.

The original reason why this wasn't there is that it requires an additional SDK call to get the Subscription Names mapped to the Subscription ID's, then each resources needs to be processed and matched up, but I agree it's a necessary process.

**Comment by XtratusCloud** [comment]
Hi @DCMattyG ,
I have tested the existing implementation in the "vwan-support" branch and it covers the needs perfectly.
This request can be closed when you publish the new version.

Regard,

**Comment by DCMattyG** [comment]
Hey there @XtratusCloud, this request has been merged into main via PR #113. Thank you for your continued support and contributions!
